import type { DemoConversation } from './types'

export const DEMO_CONVERSATIONS: DemoConversation[] = [
  // 1. Marcus Weber — Perfect tenant conversation
  {
    id: 'conv-marcus-weber',
    enquirerId: 'enq-marcus-weber',
    enquirerName: 'Marcus Weber',
    status: 'Completed',
    startedAt: '2026-02-19T10:05:00Z',
    completedAt: '2026-02-19T10:35:00Z',
    messages: [
      { id: 'mw-1', sender: 'ai', content: 'Hello Marcus, thank you for your interest in Unit 1A at London Kensington Serviced Apartments. I\'m the AI pre-qualification assistant for this property. I\'d like to ask you a few questions to help us assess your application. Shall we begin?', timestamp: '2026-02-19T10:05:00Z' },
      { id: 'mw-2', sender: 'applicant', content: 'Yes, happy to answer your questions. I\'m keen to move quickly on this if the apartment is suitable.', timestamp: '2026-02-19T10:06:00Z' },
      { id: 'mw-3', sender: 'ai', content: 'Great. Let\'s start with your timeline. When are you looking to move in, and is there a specific reason for the timing?', timestamp: '2026-02-19T10:07:00Z' },
      { id: 'mw-4', sender: 'applicant', content: 'I\'m looking to move by mid-March if possible. My current lease in the City ends on 31 March, but I\'d prefer to be settled before then. I\'m relocating from EC2 to be closer to my partner in West London.', timestamp: '2026-02-19T10:08:00Z' },
      { id: 'mw-5', sender: 'ai', content: 'Thank you. Unit 1A is available from 15 March, which aligns well. Can you tell me about your current employment? Who is your employer, your role, and how long you\'ve been there?', timestamp: '2026-02-19T10:09:00Z' },
      { id: 'mw-6', sender: 'applicant', content: 'I\'m VP of Strategy at Deutsche Bank. I\'ve been there for 6 years — started as an Analyst, promoted through to VP. Based at the London office in the City.', timestamp: '2026-02-19T10:10:00Z' },
      { id: 'mw-7', sender: 'ai', content: 'Excellent. And could you confirm your annual salary or income range? This helps us assess affordability against the rent.', timestamp: '2026-02-19T10:11:00Z' },
      { id: 'mw-8', sender: 'applicant', content: 'My base salary is £95,000 per annum. I also receive an annual bonus, typically 20-30% of base, but I understand you\'d assess on base salary.', timestamp: '2026-02-19T10:12:00Z' },
      { id: 'mw-9', sender: 'ai', content: 'That\'s helpful. At £95,000 base against £1,850 PCM, your rent-to-income ratio is approximately 23%, which is very comfortable. Now, could you tell me about your current living situation? Do you rent, and if so, who is your current landlord?', timestamp: '2026-02-19T10:14:00Z' },
      { id: 'mw-10', sender: 'applicant', content: 'Yes, I rent a 1-bed flat in EC2 managed by Grainger PLC. I\'ve been there for 3 years with no issues — happy to provide a landlord reference. Before that, I was in Frankfurt for a year when I first joined DB.', timestamp: '2026-02-19T10:15:00Z' },
      { id: 'mw-11', sender: 'ai', content: 'That\'s a clean tenancy history. One more question — are you enquiring about any other properties at the moment, or is this your primary focus?', timestamp: '2026-02-19T10:17:00Z' },
      { id: 'mw-12', sender: 'applicant', content: 'This is the only property I\'m looking at. I\'ve been watching the Holland Road area for a few weeks and this unit ticks all the boxes — location, size, and price are all right.', timestamp: '2026-02-19T10:18:00Z' },
      { id: 'mw-13', sender: 'ai', content: 'That\'s great to hear. Finally, would you be willing to provide employment documents and a landlord reference as part of the verification process?', timestamp: '2026-02-19T10:19:00Z' },
      { id: 'mw-14', sender: 'applicant', content: 'Absolutely. I can send over my employment contract, a recent payslip, and Grainger\'s contact details today. I\'d also like to book a viewing at the earliest convenience.', timestamp: '2026-02-19T10:20:00Z' },
      { id: 'mw-15', sender: 'ai', content: 'Wonderful. Thank you Marcus. Based on our conversation, your profile looks very strong. I\'ll now generate a pre-qualification assessment and our lettings team will be in touch within 24 hours to arrange a viewing. Is there anything else you\'d like to know about the property?', timestamp: '2026-02-19T10:21:00Z' },
    ],
    outcome: {
      score: 94,
      category: 'Priority',
      lines: [
        { text: 'Employment verified — Deutsche Bank VP, 6 years tenure', status: 'pass' },
        { text: 'Income comfortable — 23.4% rent-to-income ratio', status: 'pass' },
        { text: 'Single property focus — no competing enquiries', status: 'pass' },
        { text: 'Immediate timeline — aligned with unit availability', status: 'pass' },
        { text: 'Previous landlord reference available (Grainger PLC)', status: 'pass' },
      ],
    },
  },

  // 2. Aisha Patel
  {
    id: 'conv-aisha-patel',
    enquirerId: 'enq-aisha-patel',
    enquirerName: 'Aisha Patel',
    status: 'Completed',
    startedAt: '2026-02-16T12:00:00Z',
    completedAt: '2026-02-16T12:28:00Z',
    messages: [
      { id: 'ap-1', sender: 'ai', content: 'Hello Aisha, thank you for enquiring about Unit 2C at London Kensington Serviced Apartments. I\'m the AI pre-qualification assistant. Can I ask you a few questions about your application?', timestamp: '2026-02-16T12:00:00Z' },
      { id: 'ap-2', sender: 'applicant', content: 'Of course. I\'m a solicitor so I appreciate a thorough process!', timestamp: '2026-02-16T12:01:00Z' },
      { id: 'ap-3', sender: 'ai', content: 'Perfect. When are you looking to move, and what\'s prompting the move?', timestamp: '2026-02-16T12:02:00Z' },
      { id: 'ap-4', sender: 'applicant', content: 'I\'m looking to move in April. I\'m currently in a flatshare in Marylebone but after my promotion to Senior Associate, I\'d like my own place. Kensington is well-connected to the Clifford Chance office in Canary Wharf.', timestamp: '2026-02-16T12:03:00Z' },
      { id: 'ap-5', sender: 'ai', content: 'Congratulations on the promotion. Could you confirm your employer, role, and how long you\'ve been there?', timestamp: '2026-02-16T12:04:00Z' },
      { id: 'ap-6', sender: 'applicant', content: 'Clifford Chance LLP, Senior Associate in Corporate M&A. I\'ve been at the firm for 5 years — trained there and qualified in 2021. I\'m on the SRA register if you need to verify.', timestamp: '2026-02-16T12:05:00Z' },
      { id: 'ap-7', sender: 'ai', content: 'That\'s very helpful. And your annual salary?', timestamp: '2026-02-16T12:06:00Z' },
      { id: 'ap-8', sender: 'applicant', content: '£78,000 base. Bonus is discretionary but has been 15-20% the last two years.', timestamp: '2026-02-16T12:07:00Z' },
      { id: 'ap-9', sender: 'ai', content: 'At £78,000 base with £2,200 PCM rent, the ratio is about 33.8% — slightly above our 30% comfort zone on base, but within acceptable range for your career trajectory. What\'s your current tenancy situation?', timestamp: '2026-02-16T12:09:00Z' },
      { id: 'ap-10', sender: 'applicant', content: 'I rent a room in a shared flat in W1H through Fizzy Living. Been there 2 years. Happy to provide a reference. Before that, I was in E14 during my training contract years.', timestamp: '2026-02-16T12:10:00Z' },
      { id: 'ap-11', sender: 'ai', content: 'Thank you Aisha. Your profile is strong. I\'ll generate your assessment and our team will arrange a viewing. Would you like to see the property this week?', timestamp: '2026-02-16T12:12:00Z' },
      { id: 'ap-12', sender: 'applicant', content: 'Yes please, I\'m available Saturday morning or any evening after 7pm. Looking forward to it.', timestamp: '2026-02-16T12:13:00Z' },
    ],
    outcome: {
      score: 87,
      category: 'Priority',
      lines: [
        { text: 'Employment verified — Clifford Chance Senior Associate, SRA registered', status: 'pass' },
        { text: 'Income adequate — 33.8% ratio, within tolerance for professional growth', status: 'pass' },
        { text: 'Clear move motivation — promotion-driven upgrade', status: 'pass' },
        { text: 'Rent ratio slightly above 30% comfort threshold', status: 'warn' },
      ],
    },
  },

  // 3. Sophie Laurent
  {
    id: 'conv-sophie-laurent',
    enquirerId: 'enq-sophie-laurent',
    enquirerName: 'Sophie Laurent',
    status: 'Completed',
    startedAt: '2026-02-22T12:00:00Z',
    completedAt: '2026-02-22T12:25:00Z',
    messages: [
      { id: 'sl-1', sender: 'ai', content: 'Hello Sophie, thanks for your interest in Unit 3B. I\'m the AI pre-qualification assistant. Shall we go through a few questions?', timestamp: '2026-02-22T12:00:00Z' },
      { id: 'sl-2', sender: 'applicant', content: 'Sure thing. Happy to help with whatever you need.', timestamp: '2026-02-22T12:01:00Z' },
      { id: 'sl-3', sender: 'ai', content: 'When are you looking to move, and what\'s driving the change?', timestamp: '2026-02-22T12:02:00Z' },
      { id: 'sl-4', sender: 'applicant', content: 'I need to move by end of March. I\'m currently in Greenwich — SE10 — and the commute to Kings Cross is killing me. W14 has the Overground link to Kings Cross and is much more my vibe. I work at Google\'s KGX campus.', timestamp: '2026-02-22T12:03:00Z' },
      { id: 'sl-5', sender: 'ai', content: 'That makes sense. Can you tell me about your role and how long you\'ve been at Google?', timestamp: '2026-02-22T12:04:00Z' },
      { id: 'sl-6', sender: 'applicant', content: 'Product Manager, 4 years at Google London. I transferred from the Paris office — I\'m French originally but have UK settled status. I manage a team of 8 working on Google Maps features.', timestamp: '2026-02-22T12:05:00Z' },
      { id: 'sl-7', sender: 'ai', content: 'And your annual salary, if you don\'t mind sharing?', timestamp: '2026-02-22T12:06:00Z' },
      { id: 'sl-8', sender: 'applicant', content: '£115,000 base, plus RSUs. But base alone should more than cover the rent.', timestamp: '2026-02-22T12:07:00Z' },
      { id: 'sl-9', sender: 'ai', content: 'Absolutely — at £115K base against £3,100 PCM, your rent ratio is about 14%, which is exceptionally comfortable. Any current tenancy details?', timestamp: '2026-02-22T12:08:00Z' },
      { id: 'sl-10', sender: 'applicant', content: 'I rent through L&Q Housing in Greenwich. 2-year tenancy, no issues. They can provide a reference. I\'m also happy to share my employment contract and recent payslips proactively.', timestamp: '2026-02-22T12:09:00Z' },
      { id: 'sl-11', sender: 'ai', content: 'Excellent. Your profile is very strong, Sophie. I\'ll pass this through for assessment and our team will contact you shortly about viewing arrangements.', timestamp: '2026-02-22T12:10:00Z' },
    ],
    outcome: {
      score: 91,
      category: 'Priority',
      lines: [
        { text: 'Employment verified — Google Product Manager, 4 years', status: 'pass' },
        { text: 'Exceptional affordability — 14.3% rent-to-income ratio', status: 'pass' },
        { text: 'Clear commute-driven motivation', status: 'pass' },
        { text: 'Proactive document provision — high engagement signal', status: 'pass' },
      ],
    },
  },

  // 4. Tom Richards — BAD ACTOR, evasive
  {
    id: 'conv-tom-richards',
    enquirerId: 'enq-tom-richards',
    enquirerName: 'Tom Richards',
    status: 'Flagged',
    startedAt: '2026-02-14T10:00:00Z',
    completedAt: '2026-02-14T10:45:00Z',
    messages: [
      { id: 'tr-1', sender: 'ai', content: 'Hello Tom, thanks for your enquiry about Unit 8C. I\'m the AI pre-qualification assistant. Can I ask you a few questions to help assess your application?', timestamp: '2026-02-14T10:00:00Z' },
      { id: 'tr-2', sender: 'applicant', content: 'Yeah sure go ahead', timestamp: '2026-02-14T10:03:00Z' },
      { id: 'tr-3', sender: 'ai', content: 'When are you looking to move, and what\'s driving the move?', timestamp: '2026-02-14T10:04:00Z' },
      { id: 'tr-4', sender: 'applicant', content: 'ASAP really. Just need a new place. Current situation isn\'t working out.', timestamp: '2026-02-14T10:07:00Z' },
      { id: 'tr-5', sender: 'ai', content: 'I understand. Could you tell me a bit more about your current situation? Are you renting currently, and who is your landlord?', timestamp: '2026-02-14T10:08:00Z' },
      { id: 'tr-6', sender: 'applicant', content: 'Yeah I\'m renting in Fulham. It\'s a private landlord, they\'re abroad so I can\'t really get a reference from them easily. It\'s a bit complicated.', timestamp: '2026-02-14T10:10:00Z' },
      { id: 'tr-7', sender: 'ai', content: 'I see. Could you share the landlord\'s name or the letting agency managing the property? We can reach out on your behalf.', timestamp: '2026-02-14T10:11:00Z' },
      { id: 'tr-8', sender: 'applicant', content: 'There\'s no agency, it\'s direct with the landlord. I\'d rather not give their details right now if that\'s ok. Can we focus on the new place?', timestamp: '2026-02-14T10:13:00Z' },
      { id: 'tr-9', sender: 'ai', content: 'Of course. Let\'s move on to employment. Who is your employer, your role, and how long have you been there?', timestamp: '2026-02-14T10:14:00Z' },
      { id: 'tr-10', sender: 'applicant', content: 'I\'m Head of Growth at TechStartup Ltd. It\'s a tech company, we do digital marketing and growth consulting. Been there about a year.', timestamp: '2026-02-14T10:16:00Z' },
      { id: 'tr-11', sender: 'ai', content: 'Thank you. Could you share the company\'s website or Companies House registration number so we can verify the employer?', timestamp: '2026-02-14T10:17:00Z' },
      { id: 'tr-12', sender: 'applicant', content: 'We\'re still building the website actually. It\'s a startup, only been going a few months. But the business is solid, we have good clients. I don\'t have the Companies House number to hand.', timestamp: '2026-02-14T10:20:00Z' },
      { id: 'tr-13', sender: 'ai', content: 'I understand it\'s a young company. What is your annual salary at TechStartup Ltd?', timestamp: '2026-02-14T10:21:00Z' },
      { id: 'tr-14', sender: 'applicant', content: 'About £52,000. But I also do some freelance work on the side so actual income is higher, probably closer to £65k.', timestamp: '2026-02-14T10:23:00Z' },
      { id: 'tr-15', sender: 'ai', content: 'I note earlier in your enquiry form you listed your income as £58,000. Could you clarify the discrepancy between £52,000, £58,000, and £65,000?', timestamp: '2026-02-14T10:24:00Z' },
      { id: 'tr-16', sender: 'applicant', content: 'Oh right, yeah, the £58k was including some freelance. The base is £52k from TechStartup and then the rest is variable. It depends on the month really.', timestamp: '2026-02-14T10:27:00Z' },
      { id: 'tr-17', sender: 'ai', content: 'Thank you for clarifying. I should let you know that we\'ve detected your enquiry across multiple other letting agents in the W14 and SW7 area. Could you tell me more about your search?', timestamp: '2026-02-14T10:28:00Z' },
      { id: 'tr-18', sender: 'applicant', content: 'I mean, everyone looks at a few places right? I\'m just keeping my options open. Nothing wrong with that.', timestamp: '2026-02-14T10:30:00Z' },
      { id: 'tr-19', sender: 'ai', content: 'Absolutely, it\'s normal to explore options. We\'ve identified 8 active enquiries which is above the typical range. This combined with the employer verification challenges means we\'ll need to flag your application for manual review by our lettings team. They\'ll be in touch to discuss next steps and any additional documentation that might help strengthen your application.', timestamp: '2026-02-14T10:32:00Z' },
      { id: 'tr-20', sender: 'applicant', content: 'Fine whatever. I just want to see the place.', timestamp: '2026-02-14T10:35:00Z' },
    ],
    outcome: {
      score: 38,
      category: 'Low',
      lines: [
        { text: 'Employer unverifiable — "TechStartup Ltd" is a 4-month micro-entity, no website', status: 'fail' },
        { text: 'Income contradictions — stated £52K, £58K, and £65K in same conversation', status: 'fail' },
        { text: 'Multiple active enquiries detected (8) across competing agents', status: 'fail' },
        { text: 'No landlord reference available — claims landlord is "abroad"', status: 'fail' },
        { text: 'Evasive responses to verification questions throughout conversation', status: 'fail' },
      ],
    },
  },

  // 5. Oliver Reeves
  {
    id: 'conv-oliver-reeves',
    enquirerId: 'enq-oliver-reeves',
    enquirerName: 'Oliver Reeves',
    status: 'Completed',
    startedAt: '2026-02-25T11:00:00Z',
    completedAt: '2026-02-25T11:22:00Z',
    messages: [
      { id: 'or-1', sender: 'ai', content: 'Hello Oliver, thanks for your interest in Unit 5D. I\'m the AI pre-qualification assistant. Ready to go through a few questions?', timestamp: '2026-02-25T11:00:00Z' },
      { id: 'or-2', sender: 'applicant', content: 'Yes, fire away.', timestamp: '2026-02-25T11:01:00Z' },
      { id: 'or-3', sender: 'ai', content: 'What\'s your target move date, and what\'s motivating the move?', timestamp: '2026-02-25T11:02:00Z' },
      { id: 'or-4', sender: 'applicant', content: 'Looking at April. My partner works at the Design Museum in Kensington and we want to live closer. I\'m currently in Islington.', timestamp: '2026-02-25T11:03:00Z' },
      { id: 'or-5', sender: 'ai', content: 'That makes sense. Can you tell me about your employment?', timestamp: '2026-02-25T11:04:00Z' },
      { id: 'or-6', sender: 'applicant', content: 'Marketing Manager at MediaCo, a digital media agency. Been there 2 years. Before that I was at Ogilvy for 3 years. Salary is £58,000.', timestamp: '2026-02-25T11:05:00Z' },
      { id: 'or-7', sender: 'ai', content: 'Thank you. At £58,000 against £2,350 PCM, the rent-to-income ratio comes to about 48.6%, which is above our comfort threshold of 35%. Would your partner be contributing to the rent?', timestamp: '2026-02-25T11:07:00Z' },
      { id: 'or-8', sender: 'applicant', content: 'Yes, definitely. My partner earns around £45,000 so combined we\'re at £103,000 household income. We\'d split the rent. I should have mentioned that upfront — sorry.', timestamp: '2026-02-25T11:08:00Z' },
      { id: 'or-9', sender: 'ai', content: 'That helps significantly. On a combined basis the ratio drops to about 27%, which is much more comfortable. We would need your partner to be a named tenant on the agreement. Can you share your current tenancy details?', timestamp: '2026-02-25T11:10:00Z' },
      { id: 'or-10', sender: 'applicant', content: 'Sure. I rent through Grainger in N1, 2-year tenancy, all good. They can provide a reference. Partner is on a separate tenancy in Hammersmith.', timestamp: '2026-02-25T11:11:00Z' },
      { id: 'or-11', sender: 'ai', content: 'Thank you Oliver. Your application has some good strengths — solid employer, clean tenancy — but we\'ll need to factor in the joint application. I\'ll pass this through for assessment.', timestamp: '2026-02-25T11:13:00Z' },
    ],
    outcome: {
      score: 71,
      category: 'Qualified',
      lines: [
        { text: 'Employment verified — MediaCo Marketing Manager, 2 years', status: 'pass' },
        { text: 'Individual income stretched — 48.6% ratio on single salary', status: 'warn' },
        { text: 'Joint household income improves to 27% ratio — needs partner verification', status: 'warn' },
        { text: 'Clean tenancy history with Grainger', status: 'pass' },
      ],
    },
  },

  // 6. Yuki Tanaka
  {
    id: 'conv-yuki-tanaka',
    enquirerId: 'enq-yuki-tanaka',
    enquirerName: 'Yuki Tanaka',
    status: 'Completed',
    startedAt: '2026-02-21T12:00:00Z',
    completedAt: '2026-02-21T12:20:00Z',
    messages: [
      { id: 'yt-1', sender: 'ai', content: 'Hello Yuki, thanks for your interest in Unit 4A. I\'m the AI pre-qualification assistant. Ready to get started?', timestamp: '2026-02-21T12:00:00Z' },
      { id: 'yt-2', sender: 'applicant', content: 'Yes, please go ahead.', timestamp: '2026-02-21T12:01:00Z' },
      { id: 'yt-3', sender: 'ai', content: 'When are you looking to move, and what\'s the reason for the change?', timestamp: '2026-02-21T12:02:00Z' },
      { id: 'yt-4', sender: 'applicant', content: 'Mid-March ideally. I\'ve been in Canary Wharf for 2 years now and I want a change of scenery. CW is great for work but it doesn\'t feel residential enough for me. I want somewhere with more character — parks, cafes, that kind of thing.', timestamp: '2026-02-21T12:03:00Z' },
      { id: 'yt-5', sender: 'ai', content: 'Kensington certainly has that. Can you tell me about your employment situation?', timestamp: '2026-02-21T12:04:00Z' },
      { id: 'yt-6', sender: 'applicant', content: 'I\'m an Analyst at Goldman Sachs. I joined the London office 2 years ago — transferred from the Tokyo office where I did my first year. My salary is £72,000 base.', timestamp: '2026-02-21T12:05:00Z' },
      { id: 'yt-7', sender: 'ai', content: 'At £72,000 against £1,900 PCM, the ratio is about 31.7% — comfortable. What\'s your visa status, if I may ask?', timestamp: '2026-02-21T12:07:00Z' },
      { id: 'yt-8', sender: 'applicant', content: 'Tier 2 work visa, sponsored by Goldman Sachs. Valid for another 3 years. I\'m planning to apply for ILR next year.', timestamp: '2026-02-21T12:08:00Z' },
      { id: 'yt-9', sender: 'ai', content: 'Thank you. And your current tenancy in Canary Wharf?', timestamp: '2026-02-21T12:09:00Z' },
      { id: 'yt-10', sender: 'applicant', content: 'Renting through Canary Wharf Group residential management. 2-year tenancy, no issues at all. They can confirm everything.', timestamp: '2026-02-21T12:10:00Z' },
      { id: 'yt-11', sender: 'ai', content: 'Perfect. Your profile looks strong, Yuki. I\'ll generate the assessment and the team will arrange a viewing for you. Would Saturday work?', timestamp: '2026-02-21T12:11:00Z' },
      { id: 'yt-12', sender: 'applicant', content: 'Saturday morning would be ideal. Thank you!', timestamp: '2026-02-21T12:12:00Z' },
    ],
    outcome: {
      score: 79,
      category: 'Qualified',
      lines: [
        { text: 'Employment verified — Goldman Sachs Analyst, employer-sponsored visa', status: 'pass' },
        { text: 'Income comfortable — 31.7% rent-to-income ratio', status: 'pass' },
        { text: 'Clean tenancy with institutional landlord', status: 'pass' },
        { text: 'International applicant — Tier 2 visa, 3 years remaining', status: 'warn' },
      ],
    },
  },

  // 7. Elena Voronova — HIGH RISK, evasive
  {
    id: 'conv-elena-voronova',
    enquirerId: 'enq-elena-voronova',
    enquirerName: 'Elena Voronova',
    status: 'Flagged',
    startedAt: '2026-02-18T11:00:00Z',
    completedAt: '2026-02-18T11:40:00Z',
    messages: [
      { id: 'ev-1', sender: 'ai', content: 'Hello Elena, thank you for your interest in Unit 1A. I\'m the AI pre-qualification assistant. I have a few questions to help us assess your application. Shall we begin?', timestamp: '2026-02-18T11:00:00Z' },
      { id: 'ev-2', sender: 'applicant', content: 'Yes ok', timestamp: '2026-02-18T11:02:00Z' },
      { id: 'ev-3', sender: 'ai', content: 'Great. When are you looking to move, and what\'s your reason for looking at this area?', timestamp: '2026-02-18T11:03:00Z' },
      { id: 'ev-4', sender: 'applicant', content: 'Soon, like within a month. I need somewhere central. Kensington is nice area.', timestamp: '2026-02-18T11:05:00Z' },
      { id: 'ev-5', sender: 'ai', content: 'Could you tell me about your current living situation? Where do you live now, and do you rent or own?', timestamp: '2026-02-18T11:06:00Z' },
      { id: 'ev-6', sender: 'applicant', content: 'I rent in North London. N4 area. Been there about 3 years. It\'s a private rental.', timestamp: '2026-02-18T11:08:00Z' },
      { id: 'ev-7', sender: 'ai', content: 'Could you share the address or your landlord\'s details? We\'ll need a reference for the application.', timestamp: '2026-02-18T11:09:00Z' },
      { id: 'ev-8', sender: 'applicant', content: 'The landlord is abroad, I don\'t have contact details right now. I can try to find them. It\'s been informal arrangement.', timestamp: '2026-02-18T11:11:00Z' },
      { id: 'ev-9', sender: 'ai', content: 'I see. I should mention that our records show electoral roll data for your stated N4 postcode, and it doesn\'t currently show a match for your name. Could you confirm the exact address?', timestamp: '2026-02-18T11:13:00Z' },
      { id: 'ev-10', sender: 'applicant', content: 'Oh, I might not have registered there. I move around quite a bit for work. Maybe the registration is at my previous address still.', timestamp: '2026-02-18T11:15:00Z' },
      { id: 'ev-11', sender: 'ai', content: 'Understood. Let\'s move on to employment. You mentioned you\'re a consultant at "EV Consulting". Could you tell me more about the company and your role?', timestamp: '2026-02-18T11:16:00Z' },
      { id: 'ev-12', sender: 'applicant', content: 'Yes, I\'m a business consultant. I help companies with their strategy and operations. It\'s my own consultancy. I\'ve been doing it for about 2 years.', timestamp: '2026-02-18T11:18:00Z' },
      { id: 'ev-13', sender: 'ai', content: 'Is EV Consulting registered as a limited company or are you a sole trader? I wasn\'t able to find it on Companies House.', timestamp: '2026-02-18T11:19:00Z' },
      { id: 'ev-14', sender: 'applicant', content: 'It\'s in the process of being registered. I\'ve been operating as a sole trader but I\'m incorporating soon. These things take time.', timestamp: '2026-02-18T11:21:00Z' },
      { id: 'ev-15', sender: 'ai', content: 'What is your annual income from the consultancy?', timestamp: '2026-02-18T11:22:00Z' },
      { id: 'ev-16', sender: 'applicant', content: 'About £45,000. Some months are better than others but that\'s the average.', timestamp: '2026-02-18T11:24:00Z' },
      { id: 'ev-17', sender: 'ai', content: 'At £45,000 against £1,850 PCM, the rent-to-income ratio is about 49%, which is above our comfort threshold. Do you have any other income sources?', timestamp: '2026-02-18T11:25:00Z' },
      { id: 'ev-18', sender: 'applicant', content: 'I have some savings. And I\'m expecting a big contract to come through soon which will increase things a lot. Can\'t we just focus on getting me in to see the place first?', timestamp: '2026-02-18T11:27:00Z' },
      { id: 'ev-19', sender: 'ai', content: 'I understand your eagerness. However, I need to let you know that we\'ve identified several areas where we\'re unable to verify the information provided — employer not found on Companies House, no electoral roll match at your stated address, and limited professional presence online. Combined with the affordability concern, we\'ll need to flag this application for manual review by our lettings team. They\'ll be in touch to discuss what additional documentation could help strengthen your application.', timestamp: '2026-02-18T11:29:00Z' },
      { id: 'ev-20', sender: 'applicant', content: 'This is ridiculous. I\'m a genuine person looking for a flat. Not everyone has a big corporate job. You\'re discriminating against self-employed people.', timestamp: '2026-02-18T11:32:00Z' },
      { id: 'ev-21', sender: 'ai', content: 'I understand your frustration, Elena, and we absolutely do accept self-employed applicants. We have clear processes for sole traders including HMRC self-assessment returns and accountant references. If you can provide these documents, it would significantly help your application. Our team will outline exactly what\'s needed when they contact you.', timestamp: '2026-02-18T11:34:00Z' },
    ],
    outcome: {
      score: 44,
      category: 'Low',
      lines: [
        { text: 'Employer not verifiable — no Companies House record for "EV Consulting"', status: 'fail' },
        { text: 'Electoral roll mismatch — no match at claimed N4 address', status: 'fail' },
        { text: 'Income stretched — 49.3% rent-to-income ratio', status: 'fail' },
        { text: 'Evasive on landlord details and address history', status: 'fail' },
        { text: 'Phone number is registered UK mobile (only passing check)', status: 'pass' },
      ],
    },
  },

  // 8. Chris Dawson
  {
    id: 'conv-chris-dawson',
    enquirerId: 'enq-chris-dawson',
    enquirerName: 'Chris Dawson',
    status: 'Completed',
    startedAt: '2026-02-26T10:00:00Z',
    completedAt: '2026-02-26T10:18:00Z',
    messages: [
      { id: 'cd-1', sender: 'ai', content: 'Hello Chris, thanks for your enquiry. I\'m the AI pre-qualification assistant for London Kensington Serviced Apartments. Can I run through a few questions with you?', timestamp: '2026-02-26T10:00:00Z' },
      { id: 'cd-2', sender: 'applicant', content: 'Of course. I work in the industry so I know the drill!', timestamp: '2026-02-26T10:01:00Z' },
      { id: 'cd-3', sender: 'ai', content: 'That\'s great. When are you looking to move, and what\'s driving the move?', timestamp: '2026-02-26T10:02:00Z' },
      { id: 'cd-4', sender: 'applicant', content: 'I work at Foxtons Kensington so I know the area inside out. I currently live in Fulham but I\'d love to live where I work — it would save me the commute and I\'d know the building well for my own tenants. Looking at a May move.', timestamp: '2026-02-26T10:03:00Z' },
      { id: 'cd-5', sender: 'ai', content: 'Interesting perspective. Could you confirm your role and salary at Foxtons?', timestamp: '2026-02-26T10:04:00Z' },
      { id: 'cd-6', sender: 'applicant', content: 'Senior Negotiator, 3 years at the Kensington branch. Base salary is £48,000. I also earn commission which brought my total to about £67,000 last year and £62,000 the year before. But I know you\'ll assess on base.', timestamp: '2026-02-26T10:05:00Z' },
      { id: 'cd-7', sender: 'ai', content: 'You\'re right, we primarily assess on base salary. At £48,000 against even the most affordable studio at £1,800, the ratio is 45% which is stretched. Has this been a consideration for you?', timestamp: '2026-02-26T10:07:00Z' },
      { id: 'cd-8', sender: 'applicant', content: 'Honestly yes. I know the numbers are tight on base. But my commission is consistent — I\'ve been a top performer at the branch for 2 years running. I could also provide a guarantor if needed — my parents own their home in Surrey outright.', timestamp: '2026-02-26T10:08:00Z' },
      { id: 'cd-9', sender: 'ai', content: 'A guarantor option is helpful to note. What\'s your current tenancy situation?', timestamp: '2026-02-26T10:09:00Z' },
      { id: 'cd-10', sender: 'applicant', content: 'Renting a flat in SW6 through a private landlord. Been there 2 years, all payments on time. Happy to provide a reference and bank statements showing consistent rent payments.', timestamp: '2026-02-26T10:10:00Z' },
      { id: 'cd-11', sender: 'ai', content: 'Thank you Chris. Your application has some strong points — credible employer, area knowledge, clean tenancy — but the affordability on base salary is the main flag. I\'ll pass this through for assessment with the guarantor option noted.', timestamp: '2026-02-26T10:12:00Z' },
    ],
    outcome: {
      score: 58,
      category: 'Medium',
      lines: [
        { text: 'Employment verified — Foxtons Senior Negotiator, 3 years', status: 'pass' },
        { text: 'Base salary stretched — 45% ratio on £48K base', status: 'warn' },
        { text: 'Commission income variable — £62-67K total but not guaranteed', status: 'warn' },
        { text: 'Guarantor option available — strengthens application', status: 'pass' },
        { text: 'Clean tenancy history — 2 years, no issues', status: 'pass' },
      ],
    },
  },
]
