import type { DemoEnquirer } from './types'

/**
 * 12 Key Enquirer Profiles — Full Enrichment Data
 * These are the demo centrepieces with complete tenant summaries,
 * quality breakdowns, intent timelines, and consistency checks.
 */
export const KEY_ENQUIRERS: DemoEnquirer[] = [
  // 1. Marcus Weber — Perfect tenant, Score 94
  {
    id: 'enq-marcus-weber',
    firstName: 'Marcus',
    lastName: 'Weber',
    fullName: 'Marcus Weber',
    email: 'marcus.weber@deutschebank.com',
    phone: '+447911234001',
    employer: 'Deutsche Bank',
    role: 'VP Strategy',
    annualIncome: 95000,
    aiScore: 94,
    intentScore: 92,
    riskLevel: 'Low',
    pipelineStatus: 'Verified',
    verificationStatus: 'Verified',
    daysInPipeline: 8,
    linkedUnit: '1A',
    area: 'Kensington',
    conversationId: 'conv-marcus-weber',
    tenantSummary: 'Marcus Weber is a VP of Strategy at Deutsche Bank, verified via LinkedIn and Companies House directorship records. He has been employed at Deutsche Bank for 6 years with a clear career progression from Analyst to VP. His annual salary of £95,000 comfortably supports the £1,850 PCM rent on Unit 1A (23% rent-to-income ratio). Electoral roll confirms current address in EC2 (City of London) since 2021. Clean credit history with no CCJs or adverse records. Single property enquiry with immediate engagement — classic high-quality relocator profile. Previous landlord reference from Grainger PLC confirms 3-year tenancy with no issues.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 24, maxScore: 25, evidence: '6 years at Deutsche Bank, VP level. Verified via LinkedIn and Companies House directorship.' },
      { name: 'Income-to-Rent Ratio', score: 19, maxScore: 20, evidence: '£95K annual / £1,850 PCM = 23.4% ratio. Well within 30% comfort threshold.' },
      { name: 'Address History', score: 14, maxScore: 15, evidence: 'Electoral roll match at EC2 address since 2021. Previous address in Frankfurt (relocation to London).' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'Deutsche Bank — FTSE-listed multinational. Companies House confirms active UK entity.' },
      { name: 'Digital Footprint', score: 9, maxScore: 10, evidence: 'Professional LinkedIn (500+ connections), consistent employment history, corporate email domain.' },
      { name: 'Reference Signals', score: 13, maxScore: 15, evidence: 'Previous landlord reference from Grainger PLC confirms clean 3-year tenancy. No late payments.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-19T09:15:00Z', event: 'Viewed Unit 1A listing on Rightmove', type: 'positive' },
      { timestamp: '2026-02-19T09:22:00Z', event: 'Submitted enquiry within 7 minutes of first view', type: 'positive' },
      { timestamp: '2026-02-19T10:05:00Z', event: 'Engaged with AI qualifier — answered all questions directly', type: 'positive' },
      { timestamp: '2026-02-19T14:30:00Z', event: 'Requested viewing slot for earliest available date', type: 'positive' },
      { timestamp: '2026-02-20T11:00:00Z', event: 'Provided employment documents proactively', type: 'positive' },
      { timestamp: '2026-02-21T16:00:00Z', event: 'Single property enquiry — no competing applications detected', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Marcus Weber — VP Strategy, Deutsche Bank. Profile active since 2015.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Deutsche Bank confirmed. 6 years tenure, promoted from Associate to VP.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'Deutsche Bank AG London Branch — active entity, 5,000+ employees.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at EC2R address since March 2021.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (O2), registered contract — not VOIP or prepaid.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'deutschebank.com — corporate domain, MX records verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£95K is within expected range for VP Strategy at a Tier 1 investment bank (£85K-£120K).' },
    ],
  },

  // 2. Aisha Patel — Score 87, Clifford Chance Senior Associate
  {
    id: 'enq-aisha-patel',
    firstName: 'Aisha',
    lastName: 'Patel',
    fullName: 'Aisha Patel',
    email: 'aisha.patel@cliffordchance.com',
    phone: '+447911234002',
    employer: 'Clifford Chance',
    role: 'Senior Associate',
    annualIncome: 78000,
    aiScore: 87,
    intentScore: 85,
    riskLevel: 'Low',
    pipelineStatus: 'Viewing Complete',
    verificationStatus: 'Verified',
    daysInPipeline: 12,
    linkedUnit: '2C',
    area: 'Kensington',
    conversationId: 'conv-aisha-patel',
    tenantSummary: 'Aisha Patel is a Senior Associate at Clifford Chance LLP, one of the Magic Circle law firms. Verified on the SRA (Solicitors Regulation Authority) register — practising certificate current and in good standing. 5 years PQE in corporate M&A. Annual salary of £78,000 supports the £2,200 PCM rent on Unit 2C with a comfortable 33.8% ratio. Electoral roll confirms current W1 address. Moving from a flatshare to her own apartment — upgrading lifestyle after promotion. Engaged positively throughout the qualification process.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 23, maxScore: 25, evidence: '5 years at Clifford Chance. SRA register confirms practising certificate. Clear career progression.' },
      { name: 'Income-to-Rent Ratio', score: 16, maxScore: 20, evidence: '£78K annual / £2,200 PCM = 33.8% ratio. Slightly above 30% but acceptable for professional growth trajectory.' },
      { name: 'Address History', score: 13, maxScore: 15, evidence: 'Electoral roll match at W1 address since 2023. Previous address in E14 (2020-2023).' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'Clifford Chance LLP — Magic Circle firm. Companies House confirms active LLP, 3,000+ UK staff.' },
      { name: 'Digital Footprint', score: 9, maxScore: 10, evidence: 'LinkedIn professional profile, SRA register listed, Chambers & Partners mention.' },
      { name: 'Reference Signals', score: 11, maxScore: 15, evidence: 'Current landlord reference pending. Previous tenancy at Fizzy Living E14 — clean record on file.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-15T18:30:00Z', event: 'Viewed Unit 2C listing', type: 'positive' },
      { timestamp: '2026-02-15T19:00:00Z', event: 'Submitted enquiry — detailed requirements in message', type: 'positive' },
      { timestamp: '2026-02-16T12:00:00Z', event: 'Completed AI qualifier conversation — clear and direct', type: 'positive' },
      { timestamp: '2026-02-18T10:00:00Z', event: 'Attended viewing — asked detailed questions about lease terms', type: 'positive' },
      { timestamp: '2026-02-19T09:00:00Z', event: 'Followed up asking about move-in flexibility', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Aisha Patel — Senior Associate, Corporate M&A, Clifford Chance LLP.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Clifford Chance LLP confirmed. 5 years tenure.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'Clifford Chance LLP — active LLP, registered London EC4.' },
      { field: 'SRA Register', source: 'SRA', result: 'Match', detail: 'Practising certificate current. No disciplinary records.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at W1H address since 2023.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (EE), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'cliffordchance.com — corporate domain verified.' },
    ],
  },

  // 3. Sophie Laurent — Score 91, Google PM
  {
    id: 'enq-sophie-laurent',
    firstName: 'Sophie',
    lastName: 'Laurent',
    fullName: 'Sophie Laurent',
    email: 'sophie.laurent@google.com',
    phone: '+447911234003',
    employer: 'Google',
    role: 'Product Manager',
    annualIncome: 115000,
    aiScore: 91,
    intentScore: 88,
    riskLevel: 'Low',
    pipelineStatus: 'Verification In Progress',
    verificationStatus: 'Verifying',
    daysInPipeline: 5,
    linkedUnit: '3B',
    area: 'Kensington',
    conversationId: 'conv-sophie-laurent',
    tenantSummary: 'Sophie Laurent is a Product Manager at Google, based at the Kings Cross campus. Annual salary of £115,000 gives an exceptionally comfortable 14% rent-to-income ratio for Unit 3B at £3,100 PCM. Moving from SE10 (Greenwich) to W14 to reduce commute. French national with UK settled status. Electoral roll confirms SE10 address since 2022. LinkedIn profile shows 4 years at Google after transferring from Google Paris. Strong digital footprint with conference speaking credits and published articles. Single property focus — no competing enquiries detected.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 23, maxScore: 25, evidence: '4 years at Google London (transferred from Google Paris). Senior IC track.' },
      { name: 'Income-to-Rent Ratio', score: 20, maxScore: 20, evidence: '£115K annual / £3,100 PCM = 14.3% ratio. Exceptionally comfortable.' },
      { name: 'Address History', score: 13, maxScore: 15, evidence: 'Electoral roll match at SE10 since 2022. Previous: Paris (Google transfer).' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'Google LLC — Alphabet subsidiary. Companies House confirms UK entity.' },
      { name: 'Digital Footprint', score: 10, maxScore: 10, evidence: 'Strong LinkedIn (700+ connections), conference speaker, published articles, Google developer profile.' },
      { name: 'Reference Signals', score: 10, maxScore: 15, evidence: 'Current landlord reference requested — awaiting response from L&Q Housing.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-22T08:00:00Z', event: 'Viewed Unit 3B listing on Zoopla', type: 'positive' },
      { timestamp: '2026-02-22T08:15:00Z', event: 'Submitted enquiry — mentioned specific move date', type: 'positive' },
      { timestamp: '2026-02-22T12:00:00Z', event: 'Completed AI qualifier in one session', type: 'positive' },
      { timestamp: '2026-02-23T10:00:00Z', event: 'Provided employment verification docs same day', type: 'positive' },
      { timestamp: '2026-02-24T09:00:00Z', event: 'Asked about parking facilities — detailed lifestyle question', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Sophie Laurent — Product Manager, Google. Active profile with detailed work history.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Google confirmed. 4 years at Google London, previously Google Paris.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'Google UK Ltd — active entity, registered London.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at SE10 address since 2022.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (Three), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'google.com — corporate domain verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£115K is within range for Senior PM at Google London (£100K-£140K base).' },
    ],
  },

  // 4. Tom Richards — Score 38, BAD ACTOR, all checks fail
  {
    id: 'enq-tom-richards',
    firstName: 'Tom',
    lastName: 'Richards',
    fullName: 'Tom Richards',
    email: 'tom.r.richards@protonmail.com',
    phone: '+447441999888',
    employer: 'TechStartup Ltd',
    role: 'Head of Growth',
    annualIncome: 52000,
    aiScore: 38,
    intentScore: 45,
    riskLevel: 'High',
    pipelineStatus: 'Flagged',
    verificationStatus: 'Failed',
    daysInPipeline: 14,
    linkedUnit: '8C',
    area: 'Kensington',
    conversationId: 'conv-tom-richards',
    tenantSummary: 'Tom Richards claims to be Head of Growth at "TechStartup Ltd" with an annual income of £52,000. Multiple red flags identified across all verification channels. LinkedIn profile is sparse with only 23 connections and was created 3 months ago — no prior work history visible. Companies House shows "TechStartup Ltd" was incorporated just 4 months ago as a micro-entity with no filed accounts. Electoral roll shows no match at the claimed address. Phone number is a VOIP service (not a registered UK mobile). Email is from a disposable/privacy domain (Protonmail) rather than corporate. Most critically, 8 active enquiries detected across multiple letting agents in the W14/SW7 area — a pattern consistent with fraudulent applicants who apply broadly hoping one slips through. Income of £52K would put the £1,800 PCM rent at a stretched 41.5% ratio. All consistency checks fail.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 4, maxScore: 25, evidence: 'Claimed employer "TechStartup Ltd" is a 4-month-old micro-entity. No verifiable work history.' },
      { name: 'Income-to-Rent Ratio', score: 8, maxScore: 20, evidence: '£52K annual / £1,800 PCM = 41.5% ratio. Significantly above 35% high-risk threshold.' },
      { name: 'Address History', score: 3, maxScore: 15, evidence: 'No electoral roll match. Claimed address shows different registered occupant.' },
      { name: 'Employer Credibility', score: 2, maxScore: 15, evidence: 'TechStartup Ltd — micro-entity, 4 months old, no accounts filed, single director.' },
      { name: 'Digital Footprint', score: 3, maxScore: 10, evidence: 'Sparse LinkedIn (23 connections, 3 months old). No other professional presence found.' },
      { name: 'Reference Signals', score: 2, maxScore: 15, evidence: 'No landlord references provided. 8 active enquiries detected across other agents.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-13T22:45:00Z', event: 'Submitted enquiry at 10:45 PM — unusual timing', type: 'negative' },
      { timestamp: '2026-02-14T10:00:00Z', event: 'AI qualifier started — delayed responses, evasive on employer details', type: 'negative' },
      { timestamp: '2026-02-14T10:30:00Z', event: 'Contradicted earlier salary claim when questioned', type: 'negative' },
      { timestamp: '2026-02-14T11:00:00Z', event: 'Refused to provide company registration details', type: 'negative' },
      { timestamp: '2026-02-15T09:00:00Z', event: '8 active enquiries detected across Foxtons, Marsh & Parsons, Dexters', type: 'negative' },
      { timestamp: '2026-02-16T14:00:00Z', event: 'VOIP phone detected — not a registered UK mobile number', type: 'negative' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Mismatch', detail: 'LinkedIn profile for "Tom Richards" created 3 months ago. Only 23 connections. No endorsements.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Mismatch', detail: 'LinkedIn shows "Growth Consultant — Self-employed" not "TechStartup Ltd Head of Growth".' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Mismatch', detail: 'TechStartup Ltd — micro-entity, incorporated 4 months ago. No accounts filed. Single director (not Tom Richards).' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Mismatch', detail: 'No match at claimed SW6 address. Different occupant registered.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Mismatch', detail: 'VOIP number (Voipfone) — not a registered UK mobile carrier.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Mismatch', detail: 'Protonmail — privacy/disposable email service, not corporate domain.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Mismatch', detail: '£52K claimed for "Head of Growth" at a micro-entity. No industry benchmark data available for unverified company.' },
    ],
  },

  // 5. James Okafor — Score 82, Deloitte
  {
    id: 'enq-james-okafor',
    firstName: 'James',
    lastName: 'Okafor',
    fullName: 'James Okafor',
    email: 'james.okafor@deloitte.co.uk',
    phone: '+447911234005',
    employer: 'Deloitte',
    role: 'Senior Consultant',
    annualIncome: 88000,
    aiScore: 82,
    intentScore: 80,
    riskLevel: 'Low',
    pipelineStatus: 'Viewing Booked',
    verificationStatus: 'Verified',
    daysInPipeline: 6,
    linkedUnit: '3B',
    area: 'Kensington',
    tenantSummary: 'James Okafor is a Senior Consultant at Deloitte UK, specialising in technology transformation. 4 years at Deloitte with progression from Analyst to Senior Consultant. Annual salary of £88,000 supports the £3,100 PCM rent on Unit 3B with a 42.3% ratio — slightly stretched but manageable given bonus structure (typically 10-15% at Deloitte senior level). Strong digital footprint with LinkedIn presence showing 800+ connections and industry conference participation. Electoral roll confirms E1 (Whitechapel) address since 2023. Moving west for partner\'s workplace proximity.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 22, maxScore: 25, evidence: '4 years at Deloitte. Promoted from Analyst to Senior Consultant. Corporate email verified.' },
      { name: 'Income-to-Rent Ratio', score: 14, maxScore: 20, evidence: '£88K base / £3,100 PCM = 42.3% ratio. Stretched on base but with 10-15% bonus, effective ratio ~37%.' },
      { name: 'Address History', score: 13, maxScore: 15, evidence: 'Electoral roll match at E1 address since 2023. Previous address in Birmingham (university relocation).' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'Deloitte LLP — Big Four professional services. Companies House confirms active entity.' },
      { name: 'Digital Footprint', score: 9, maxScore: 10, evidence: 'LinkedIn 800+ connections, conference speaker, Deloitte Insights contributor.' },
      { name: 'Reference Signals', score: 9, maxScore: 15, evidence: 'Current landlord reference from Essential Living — positive but short tenancy (1 year).' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-21T12:00:00Z', event: 'Viewed Unit 3B listing', type: 'positive' },
      { timestamp: '2026-02-21T12:30:00Z', event: 'Enquiry submitted with partner details', type: 'positive' },
      { timestamp: '2026-02-22T10:00:00Z', event: 'Completed AI qualifier promptly', type: 'positive' },
      { timestamp: '2026-02-23T14:00:00Z', event: 'Viewing booked for next week', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'James Okafor — Senior Consultant, Technology Transformation, Deloitte.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Deloitte confirmed. 4 years tenure.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'Deloitte LLP — active entity, 20,000+ UK employees.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at E1 address since 2023.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (Vodafone), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'deloitte.co.uk — corporate domain verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£88K within range for Senior Consultant at Deloitte (£75K-£95K base).' },
    ],
  },

  // 6. Rachel Adams — Score 85, KPMG, Tenancy Signed
  {
    id: 'enq-rachel-adams',
    firstName: 'Rachel',
    lastName: 'Adams',
    fullName: 'Rachel Adams',
    email: 'rachel.adams@kpmg.co.uk',
    phone: '+447911234006',
    employer: 'KPMG',
    role: 'Audit Manager',
    annualIncome: 85000,
    aiScore: 85,
    intentScore: 90,
    riskLevel: 'Low',
    pipelineStatus: 'Tenancy Signed',
    verificationStatus: 'Verified',
    daysInPipeline: 21,
    linkedUnit: '7A',
    area: 'Kensington',
    tenantSummary: 'Rachel Adams is an Audit Manager at KPMG, verified via LinkedIn and professional membership (ICAEW). 6 years at KPMG with ACA qualification. Annual salary of £85,000 supports the £2,150 PCM rent on Unit 7A with a 30.4% ratio. Electoral roll confirms W8 (Kensington) address since 2022 — a local mover upgrading within the area. Clean tenancy history with current landlord Foxtons Management confirming no issues. Tenancy agreement signed on 25 Feb. Model journey through the pipeline.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 24, maxScore: 25, evidence: '6 years at KPMG. ACA qualified. ICAEW membership verified.' },
      { name: 'Income-to-Rent Ratio', score: 17, maxScore: 20, evidence: '£85K annual / £2,150 PCM = 30.4% ratio. At the threshold but comfortable for Big Four employee.' },
      { name: 'Address History', score: 14, maxScore: 15, evidence: 'Electoral roll match at W8 since 2022. Local mover — knows the area well.' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'KPMG LLP — Big Four firm. Companies House active. 16,000+ UK employees.' },
      { name: 'Digital Footprint', score: 8, maxScore: 10, evidence: 'LinkedIn professional profile. ICAEW member directory listing.' },
      { name: 'Reference Signals', score: 7, maxScore: 15, evidence: 'Foxtons Management landlord reference — clean 2-year tenancy, no arrears.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-06T17:00:00Z', event: 'Viewed Unit 7A listing', type: 'positive' },
      { timestamp: '2026-02-06T17:20:00Z', event: 'Enquiry submitted — mentioned local mover', type: 'positive' },
      { timestamp: '2026-02-07T11:00:00Z', event: 'Completed AI qualifier', type: 'positive' },
      { timestamp: '2026-02-10T14:00:00Z', event: 'Viewing completed — very positive feedback', type: 'positive' },
      { timestamp: '2026-02-14T10:00:00Z', event: 'Verification completed — all checks passed', type: 'positive' },
      { timestamp: '2026-02-25T15:00:00Z', event: 'Tenancy agreement signed', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Rachel Adams — Audit Manager, KPMG LLP.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'KPMG LLP confirmed. 6 years tenure.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'KPMG LLP — active entity.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at W8 address since 2022.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (EE), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'kpmg.co.uk — corporate domain verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£85K within range for Audit Manager at KPMG (£75K-£95K).' },
    ],
  },

  // 7. Oliver Reeves — Score 71, Medium risk, income stretched
  {
    id: 'enq-oliver-reeves',
    firstName: 'Oliver',
    lastName: 'Reeves',
    fullName: 'Oliver Reeves',
    email: 'oliver.reeves@mediaco.co.uk',
    phone: '+447911234007',
    employer: 'MediaCo',
    role: 'Marketing Manager',
    annualIncome: 58000,
    aiScore: 71,
    intentScore: 68,
    riskLevel: 'Medium',
    pipelineStatus: 'Scored',
    verificationStatus: 'Not Started',
    daysInPipeline: 3,
    linkedUnit: '5D',
    area: 'Kensington',
    conversationId: 'conv-oliver-reeves',
    tenantSummary: 'Oliver Reeves is a Marketing Manager at MediaCo, a mid-size digital media agency. Annual income of £58,000 against the £2,350 PCM rent gives a 48.6% rent-to-income ratio — significantly above the 35% comfort threshold. While the employer is credible (Companies House active for 8 years, 120 employees), the financial stretch presents a medium risk. LinkedIn profile confirms role and tenure (2 years). Electoral roll confirms N1 (Islington) address. Moving to Kensington for partner — reasonable motivation but the affordability question needs addressing in verification.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 18, maxScore: 25, evidence: '2 years at MediaCo. Previous role at Ogilvy (3 years). Stable trajectory.' },
      { name: 'Income-to-Rent Ratio', score: 8, maxScore: 20, evidence: '£58K annual / £2,350 PCM = 48.6% ratio. Significantly stretched. Risk factor.' },
      { name: 'Address History', score: 12, maxScore: 15, evidence: 'Electoral roll match at N1 address since 2024.' },
      { name: 'Employer Credibility', score: 12, maxScore: 15, evidence: 'MediaCo Ltd — active 8 years, 120 employees. Credible mid-size agency.' },
      { name: 'Digital Footprint', score: 8, maxScore: 10, evidence: 'LinkedIn active, industry conference attendee, marketing blog contributor.' },
      { name: 'Reference Signals', score: 13, maxScore: 15, evidence: 'Current landlord reference from Grainger — clean 2-year tenancy.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-24T14:00:00Z', event: 'Viewed Unit 5D listing', type: 'positive' },
      { timestamp: '2026-02-24T14:45:00Z', event: 'Enquiry submitted', type: 'positive' },
      { timestamp: '2026-02-25T11:00:00Z', event: 'Completed AI qualifier — honest about budget concerns', type: 'neutral' },
      { timestamp: '2026-02-25T15:00:00Z', event: 'Mentioned partner will contribute to rent — unverified', type: 'neutral' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Oliver Reeves — Marketing Manager, MediaCo.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'MediaCo confirmed. 2 years tenure.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'MediaCo Ltd — active entity, 8 years, 120 employees.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at N1 address since 2024.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (Three), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'mediaco.co.uk — corporate domain verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£58K within range for Marketing Manager at mid-size agency (£45K-£65K).' },
    ],
  },

  // 8. Yuki Tanaka — Score 79, Goldman Sachs Analyst
  {
    id: 'enq-yuki-tanaka',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    fullName: 'Yuki Tanaka',
    email: 'yuki.tanaka@gs.com',
    phone: '+447911234008',
    employer: 'Goldman Sachs',
    role: 'Analyst',
    annualIncome: 72000,
    aiScore: 79,
    intentScore: 75,
    riskLevel: 'Low',
    pipelineStatus: 'Viewing Booked',
    verificationStatus: 'Verified',
    daysInPipeline: 7,
    linkedUnit: '4A',
    area: 'Kensington',
    conversationId: 'conv-yuki-tanaka',
    tenantSummary: 'Yuki Tanaka is an Analyst at Goldman Sachs, relocating from Canary Wharf (E14) to Kensington. Japanese national with UK Tier 2 visa (employer sponsored). 2 years at Goldman Sachs London, transferred from Tokyo office. Annual salary of £72,000 supports the £1,900 PCM rent on Unit 4A with a 31.7% ratio. LinkedIn confirms role and career progression. Electoral roll shows E14 address. Clean credit history. Motivated by wanting a quieter residential area after living in Canary Wharf.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 19, maxScore: 25, evidence: '2 years at Goldman Sachs London (transferred from Tokyo). Analyst level — early career but strong employer.' },
      { name: 'Income-to-Rent Ratio', score: 16, maxScore: 20, evidence: '£72K annual / £1,900 PCM = 31.7% ratio. Comfortable.' },
      { name: 'Address History', score: 11, maxScore: 15, evidence: 'Electoral roll match at E14 since 2024. International move from Tokyo — limited UK address history.' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'Goldman Sachs International — Companies House active. Tier 1 investment bank.' },
      { name: 'Digital Footprint', score: 8, maxScore: 10, evidence: 'LinkedIn professional profile. University alumni networks. Corporate email domain.' },
      { name: 'Reference Signals', score: 10, maxScore: 15, evidence: 'Current landlord Canary Wharf Group residential — positive reference, 2-year tenancy.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-20T19:00:00Z', event: 'Viewed Unit 4A listing', type: 'positive' },
      { timestamp: '2026-02-20T19:30:00Z', event: 'Enquiry submitted — mentioned Canary Wharf relocation', type: 'positive' },
      { timestamp: '2026-02-21T12:00:00Z', event: 'Completed AI qualifier', type: 'positive' },
      { timestamp: '2026-02-22T10:00:00Z', event: 'Viewing booked for Saturday', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Yuki Tanaka — Analyst, Goldman Sachs International.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Goldman Sachs confirmed. Transferred from Tokyo 2024.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'Goldman Sachs International — active entity.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at E14 address since 2024.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (Vodafone), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'gs.com — Goldman Sachs corporate domain verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£72K within range for GS Analyst London (£65K-£85K base).' },
    ],
  },

  // 9. David Chen — Score 65, Freelance developer, Medium risk
  {
    id: 'enq-david-chen',
    firstName: 'David',
    lastName: 'Chen',
    fullName: 'David Chen',
    email: 'david@davidchendev.co.uk',
    phone: '+447911234009',
    employer: 'Self-employed',
    role: 'Freelance Software Developer',
    annualIncome: 68000,
    aiScore: 65,
    intentScore: 62,
    riskLevel: 'Medium',
    pipelineStatus: 'Scored',
    verificationStatus: 'Not Started',
    daysInPipeline: 4,
    linkedUnit: '7A',
    area: 'Kensington',
    tenantSummary: 'David Chen is a freelance software developer operating as a sole trader. Self-employed for 3 years after leaving Accenture. Annual income of £68,000 based on last two tax returns — however, as a freelancer, income is variable (ranging £55K-£82K over the past 3 years). Companies House shows no limited company — operates as sole trader. LinkedIn confirms freelance work with clients including Barclays, Tesco, and several startups. Electoral roll confirms SE1 (Southwark) address. The self-employed status and variable income present moderate risk — rental affordability depends on consistent contract flow. Currently has a 6-month contract with Barclays which provides some stability.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 14, maxScore: 25, evidence: 'Self-employed 3 years. Variable income. Previous: Accenture (4 years). Current 6-month Barclays contract.' },
      { name: 'Income-to-Rent Ratio', score: 15, maxScore: 20, evidence: '£68K average / £2,150 PCM = 37.9% ratio. Above comfort threshold, and income is variable.' },
      { name: 'Address History', score: 12, maxScore: 15, evidence: 'Electoral roll match at SE1 since 2021. Stable address history.' },
      { name: 'Employer Credibility', score: 6, maxScore: 15, evidence: 'Sole trader — no limited company. HMRC self-assessment returns provided.' },
      { name: 'Digital Footprint', score: 9, maxScore: 10, evidence: 'Strong GitHub profile (1,200+ contributions), LinkedIn active, personal website with portfolio.' },
      { name: 'Reference Signals', score: 9, maxScore: 15, evidence: 'Previous landlord Peabody Housing — clean 3-year tenancy. Accountant reference provided.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-23T15:00:00Z', event: 'Viewed Unit 7A listing', type: 'positive' },
      { timestamp: '2026-02-23T16:00:00Z', event: 'Enquiry submitted', type: 'positive' },
      { timestamp: '2026-02-24T10:00:00Z', event: 'Completed AI qualifier — transparent about self-employment', type: 'neutral' },
      { timestamp: '2026-02-25T09:00:00Z', event: 'Proactively offered tax returns and accountant details', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'David Chen — Freelance Software Developer.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Self-employed confirmed. Previous Accenture employment verified.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Unverified', detail: 'No limited company found. Sole trader — not required to register with Companies House.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at SE1 address since 2021.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (O2), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'davidchendev.co.uk — personal business domain, active for 3 years.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£68K average is within range for senior freelance developer (£55K-£90K).' },
    ],
  },

  // 10. Priya Sharma — Score 76, NHS Senior Registrar
  {
    id: 'enq-priya-sharma',
    firstName: 'Priya',
    lastName: 'Sharma',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@nhs.net',
    phone: '+447911234010',
    employer: 'NHS — Imperial College Healthcare',
    role: 'Senior Registrar',
    annualIncome: 82000,
    aiScore: 76,
    intentScore: 72,
    riskLevel: 'Low',
    pipelineStatus: 'Viewing Complete',
    verificationStatus: 'Verified',
    daysInPipeline: 15,
    linkedUnit: '9B',
    area: 'Kensington',
    tenantSummary: 'Priya Sharma is a Senior Registrar (ST7) at Imperial College Healthcare NHS Trust, based at Charing Cross Hospital. GMC registered and on the specialist register. Annual salary of £82,000 (including London weighting and on-call supplement) against the £3,400 PCM rent gives a 49.8% ratio — stretched, but NHS employment provides exceptional job security and predictable income with annual increments. 8 years in NHS training pathway. Electoral roll confirms NW1 address. Moving closer to Charing Cross Hospital to reduce commute during intensive on-call periods.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 24, maxScore: 25, evidence: '8 years NHS training pathway. GMC registered. ST7 level — 1 year from consultant appointment.' },
      { name: 'Income-to-Rent Ratio', score: 10, maxScore: 20, evidence: '£82K / £3,400 PCM = 49.8% ratio. Stretched, but NHS provides guaranteed income with annual increments.' },
      { name: 'Address History', score: 13, maxScore: 15, evidence: 'Electoral roll match at NW1 since 2023. Previous: Sheffield (training rotation).' },
      { name: 'Employer Credibility', score: 15, maxScore: 15, evidence: 'NHS — Imperial College Healthcare Trust. Public sector. GMC verified.' },
      { name: 'Digital Footprint', score: 7, maxScore: 10, evidence: 'GMC register listing. LinkedIn professional profile. Published medical research papers.' },
      { name: 'Reference Signals', score: 7, maxScore: 15, evidence: 'Current landlord reference pending. Hospital HR employment letter provided.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-12T20:00:00Z', event: 'Viewed Unit 9B listing', type: 'positive' },
      { timestamp: '2026-02-12T20:30:00Z', event: 'Enquiry submitted — mentioned hospital proximity', type: 'positive' },
      { timestamp: '2026-02-13T12:00:00Z', event: 'Completed AI qualifier', type: 'positive' },
      { timestamp: '2026-02-17T14:00:00Z', event: 'Viewing completed — positive about the space', type: 'positive' },
      { timestamp: '2026-02-20T09:00:00Z', event: 'Provided GMC and employment verification documents', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Dr Priya Sharma — Senior Registrar, Imperial College Healthcare NHS Trust.' },
      { field: 'Employer vs GMC Register', source: 'GMC', result: 'Match', detail: 'GMC registered. Specialist register — General Surgery. Licence to practise: Active.' },
      { field: 'Employer vs NHS', source: 'NHS ESR', result: 'Match', detail: 'Imperial College Healthcare NHS Trust — employment confirmed.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at NW1 address since 2023.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (EE), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'nhs.net — official NHS email domain.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£82K within range for ST7 with London weighting (£75K-£90K).' },
    ],
  },

  // 11. Elena Voronova — Score 44, High risk, Flagged
  {
    id: 'enq-elena-voronova',
    firstName: 'Elena',
    lastName: 'Voronova',
    fullName: 'Elena Voronova',
    email: 'elena.v.consulting@gmail.com',
    phone: '+447700900123',
    employer: 'EV Consulting',
    role: 'Consultant',
    annualIncome: 45000,
    aiScore: 44,
    intentScore: 40,
    riskLevel: 'High',
    pipelineStatus: 'Flagged',
    verificationStatus: 'Failed',
    daysInPipeline: 10,
    linkedUnit: '1A',
    area: 'Kensington',
    conversationId: 'conv-elena-voronova',
    tenantSummary: 'Elena Voronova claims to be a consultant at "EV Consulting" with an annual income of £45,000. Multiple verification flags raised. LinkedIn profile is thin — 15 connections, minimal work history, profile created 6 weeks ago. No Companies House record for "EV Consulting" as either a limited company or LLP. Electoral roll shows no match at claimed N4 address — a different occupant is registered. Income of £45,000 against £1,850 PCM rent gives a 49.3% ratio — significantly stretched. Phone number is a registered UK mobile but email is a generic Gmail address rather than corporate. Inconsistent address history — claimed 3 years at current address but electoral roll shows only 6 months at a different N4 property. Overall pattern suggests fabricated or significantly embellished application.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 5, maxScore: 25, evidence: 'Claims "EV Consulting" but no verifiable employer. LinkedIn profile thin and recently created.' },
      { name: 'Income-to-Rent Ratio', score: 7, maxScore: 20, evidence: '£45K / £1,850 PCM = 49.3% ratio. Significantly above risk threshold.' },
      { name: 'Address History', score: 4, maxScore: 15, evidence: 'Electoral roll mismatch. Claimed address does not match records.' },
      { name: 'Employer Credibility', score: 3, maxScore: 15, evidence: 'No Companies House record for "EV Consulting". Unverifiable employer.' },
      { name: 'Digital Footprint', score: 3, maxScore: 10, evidence: 'Thin LinkedIn (15 connections, 6 weeks old). Gmail email. No professional web presence.' },
      { name: 'Reference Signals', score: 4, maxScore: 15, evidence: 'No landlord references provided. Claims "private landlord" who is "abroad".' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-17T21:30:00Z', event: 'Submitted enquiry at 9:30 PM', type: 'neutral' },
      { timestamp: '2026-02-18T11:00:00Z', event: 'AI qualifier started — vague about employer specifics', type: 'negative' },
      { timestamp: '2026-02-18T11:20:00Z', event: 'Contradicted address details when cross-referenced', type: 'negative' },
      { timestamp: '2026-02-18T11:30:00Z', event: 'Became evasive about previous tenancy details', type: 'negative' },
      { timestamp: '2026-02-19T10:00:00Z', event: 'No Companies House record found for claimed employer', type: 'negative' },
      { timestamp: '2026-02-20T09:00:00Z', event: 'Electoral roll mismatch confirmed', type: 'negative' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Mismatch', detail: 'LinkedIn "Elena V" — profile 6 weeks old, 15 connections, minimal detail.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Mismatch', detail: 'LinkedIn shows "Independent Consultant" — no "EV Consulting" mentioned.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Mismatch', detail: 'No record found for "EV Consulting" as Ltd, LLP, or sole trader.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Mismatch', detail: 'No match at claimed N4 address. Different occupant registered.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (O2), registered contract. (Only passing check)' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Mismatch', detail: 'Gmail — generic consumer email, not corporate domain.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Unverified', detail: 'Cannot benchmark — no verifiable employer or role to compare against.' },
    ],
  },

  // 12. Chris Dawson — Score 58, Foxtons estate agent, Medium risk
  {
    id: 'enq-chris-dawson',
    firstName: 'Chris',
    lastName: 'Dawson',
    fullName: 'Chris Dawson',
    email: 'chris.dawson@foxtons.co.uk',
    phone: '+447911234012',
    employer: 'Foxtons',
    role: 'Senior Negotiator',
    annualIncome: 48000,
    aiScore: 58,
    intentScore: 55,
    riskLevel: 'Medium',
    pipelineStatus: 'Scored',
    verificationStatus: 'Not Started',
    daysInPipeline: 2,
    linkedUnit: null,
    area: 'Kensington',
    conversationId: 'conv-chris-dawson',
    tenantSummary: 'Chris Dawson is a Senior Negotiator at Foxtons estate agency. Annual base salary of £48,000 (with commission potentially bringing total to £60-70K, but commission is variable and unpredictable). Base salary against even the cheapest available studio at £1,800 PCM gives a 45% ratio — stretched on base. Foxtons is a credible, listed employer (Companies House active, 1,500+ employees). LinkedIn confirms 3 years at Foxtons, Kensington branch. Electoral roll confirms SW6 (Fulham) address. The main risk is affordability — Kensington rents are at the upper end for an estate agent salary. Commission variability means income is not guaranteed. However, employer credibility and area knowledge are strong positives.',
    qualityBreakdown: [
      { name: 'Employment Stability', score: 19, maxScore: 25, evidence: '3 years at Foxtons. Senior Negotiator level. Kensington branch — good local knowledge.' },
      { name: 'Income-to-Rent Ratio', score: 9, maxScore: 20, evidence: '£48K base / £1,800 PCM = 45% ratio. With commission ~£60-70K total, ratio improves to 31-36%.' },
      { name: 'Address History', score: 13, maxScore: 15, evidence: 'Electoral roll match at SW6 since 2022.' },
      { name: 'Employer Credibility', score: 13, maxScore: 15, evidence: 'Foxtons Group PLC — listed company, active on Companies House, 1,500+ employees.' },
      { name: 'Digital Footprint', score: 7, maxScore: 10, evidence: 'LinkedIn profile, Foxtons agent profile page, local property market activity.' },
      { name: 'Reference Signals', score: 7, maxScore: 15, evidence: 'Current landlord reference available. No adverse credit history.' },
    ],
    intentTimeline: [
      { timestamp: '2026-02-25T13:00:00Z', event: 'Viewed multiple listings', type: 'neutral' },
      { timestamp: '2026-02-25T13:30:00Z', event: 'Enquiry submitted — industry professional', type: 'positive' },
      { timestamp: '2026-02-26T10:00:00Z', event: 'Completed AI qualifier — knowledgeable about process', type: 'positive' },
    ],
    consistencyChecks: [
      { field: 'Name vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Chris Dawson — Senior Negotiator, Foxtons Kensington.' },
      { field: 'Employer vs LinkedIn', source: 'LinkedIn', result: 'Match', detail: 'Foxtons confirmed. 3 years tenure at Kensington branch.' },
      { field: 'Employer vs Companies House', source: 'Companies House', result: 'Match', detail: 'Foxtons Group PLC — active listed company.' },
      { field: 'Address vs Electoral Roll', source: 'Electoral Roll', result: 'Match', detail: 'Registered at SW6 address since 2022.' },
      { field: 'Phone Type', source: 'Carrier Lookup', result: 'Match', detail: 'UK mobile (Three), registered contract.' },
      { field: 'Email Domain', source: 'Domain Check', result: 'Match', detail: 'foxtons.co.uk — corporate domain verified.' },
      { field: 'Income vs Benchmarks', source: 'Salary Benchmarks', result: 'Match', detail: '£48K base is within range for Senior Negotiator (£40K-£55K base + commission).' },
    ],
  },
]
