import type { DemoProperty, DemoUnit } from './types'

export const DEMO_PROPERTY: DemoProperty = {
  name: 'London Kensington Serviced Apartments',
  address: 'Holland Road',
  postcode: 'W14 8BD',
  area: 'Kensington',
  totalUnits: 70,
  occupiedUnits: 60,
  availableUnits: 10,
  avgRent: 2450,
  occupancyRate: 85.7,
}

export const DEMO_AVAILABLE_UNITS: DemoUnit[] = [
  {
    id: 'unit-1a',
    name: '1A',
    type: 'Studio',
    rentPCM: 1850,
    availableFrom: '2026-03-15',
    status: 'Available',
    matchedLeadIds: ['enq-marcus-weber', 'enq-elena-voronova'],
  },
  {
    id: 'unit-2c',
    name: '2C',
    type: '1 Bed',
    rentPCM: 2200,
    availableFrom: '2026-04-01',
    status: 'Available',
    matchedLeadIds: ['enq-aisha-patel'],
  },
  {
    id: 'unit-3b',
    name: '3B',
    type: '2 Bed',
    rentPCM: 3100,
    availableFrom: '2026-03-20',
    status: 'Available',
    matchedLeadIds: ['enq-sophie-laurent', 'enq-james-okafor'],
  },
  {
    id: 'unit-4a',
    name: '4A',
    type: 'Studio',
    rentPCM: 1900,
    availableFrom: '2026-03-10',
    status: 'Available',
    matchedLeadIds: ['enq-yuki-tanaka'],
  },
  {
    id: 'unit-5d',
    name: '5D',
    type: '1 Bed',
    rentPCM: 2350,
    availableFrom: '2026-04-01',
    status: 'Available',
    matchedLeadIds: ['enq-oliver-reeves'],
  },
  {
    id: 'unit-6b',
    name: '6B',
    type: '2 Bed',
    rentPCM: 3250,
    availableFrom: '2026-04-15',
    status: 'Available',
    matchedLeadIds: [],
  },
  {
    id: 'unit-7a',
    name: '7A',
    type: '1 Bed',
    rentPCM: 2150,
    availableFrom: '2026-03-25',
    status: 'Available',
    matchedLeadIds: ['enq-rachel-adams', 'enq-david-chen'],
  },
  {
    id: 'unit-8c',
    name: '8C',
    type: 'Studio',
    rentPCM: 1800,
    availableFrom: '2026-04-05',
    status: 'Available',
    matchedLeadIds: ['enq-tom-richards'],
  },
  {
    id: 'unit-9b',
    name: '9B',
    type: '2 Bed',
    rentPCM: 3400,
    availableFrom: '2026-04-20',
    status: 'Available',
    matchedLeadIds: ['enq-priya-sharma'],
  },
  {
    id: 'unit-10a',
    name: '10A',
    type: '1 Bed',
    rentPCM: 2100,
    availableFrom: '2026-05-01',
    status: 'Available',
    matchedLeadIds: [],
  },
]

// Generate occupied units for building display
export const DEMO_OCCUPIED_UNITS: DemoUnit[] = Array.from({ length: 60 }, (_, i) => ({
  id: `unit-occ-${i + 1}`,
  name: `${Math.floor(i / 6) + 1}${String.fromCharCode(65 + (i % 6))}`,
  type: (['Studio', '1 Bed', '2 Bed'] as const)[i % 3],
  rentPCM: [1800, 2200, 3100][i % 3],
  availableFrom: '',
  status: 'Occupied' as const,
  matchedLeadIds: [],
}))
