/**
 * Demo Data for Smart Bricks Presentation
 *
 * Realistic sample data powering the Smart Bricks demo dashboard.
 * Use /sbricksdemo to enter presentation mode without Supabase credentials.
 */

export const SB_DEMO_COMPANY = {
  id: 'sb-demo-company-001',
  name: 'Smart Bricks',
  type: 'developer',
}

export const SB_DEMO_USER = {
  id: 'sb-demo-user-001',
  email: 'scott@smartbricks.com',
  name: 'Scott McGeachy',
  role: 'developer' as const,
  company: SB_DEMO_COMPANY.name,
  company_id: SB_DEMO_COMPANY.id,
  isDemo: true,
}

/** Dashboard stats matching the shape returned by /api/dashboard/stats */
export const SB_DEMO_BUYER_STATS = {
  total_leads: 1243,
  hot_leads: 156,
  qualified: 312,
  needs_qualification: 287,
  nurture: 324,
  low_priority: 112,
  disqualified: 52,
  avg_score: 61,
  contact_pending: 198,
  follow_up: 287,
  viewing_booked: 134,
  negotiating: 67,
  reserved: 42,
  completed: 28,
  not_proceeding: 89,
}

export const SB_DEMO_CAMPAIGN_STATS = {
  total_campaigns: 18,
  active_campaigns: 11,
  total_spend: 312000,
  total_leads: 1243,
  avg_cpl: 251.00,
}

export const SB_DEMO_DEVELOPMENTS = [
  {
    id: 'sb-dev-001',
    name: 'Dubai Marina Heights',
    location: 'Dubai Marina, Dubai',
    status: 'Active',
    total_units: 320,
    available_units: 45,
    price_from: 850000,
    price_to: 4500000,
    completion_date: 'Q1 2026',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-002',
    name: 'Palm Residences',
    location: 'Palm Jumeirah, Dubai',
    status: 'Active',
    total_units: 180,
    available_units: 22,
    price_from: 2200000,
    price_to: 12000000,
    completion_date: 'Q3 2026',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-003',
    name: 'Creek Vista',
    location: 'Dubai Creek Harbour, Dubai',
    status: 'Active',
    total_units: 450,
    available_units: 128,
    price_from: 620000,
    price_to: 3200000,
    completion_date: 'Q2 2027',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-004',
    name: 'Yas Bay Towers',
    location: 'Yas Island, Abu Dhabi',
    status: 'Active',
    total_units: 280,
    available_units: 94,
    price_from: 550000,
    price_to: 2800000,
    completion_date: 'Q4 2026',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-005',
    name: 'Saadiyat Shores',
    location: 'Saadiyat Island, Abu Dhabi',
    status: 'Active',
    total_units: 160,
    available_units: 67,
    price_from: 1800000,
    price_to: 8500000,
    completion_date: 'Q1 2027',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-006',
    name: 'Canary Wharf Place',
    location: 'Canary Wharf, London E14',
    status: 'Coming Soon',
    total_units: 240,
    available_units: 240,
    price_from: 650000,
    price_to: 3500000,
    completion_date: 'Q3 2028',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-007',
    name: 'Manhattan East',
    location: 'Lower East Side, New York',
    status: 'Coming Soon',
    total_units: 190,
    available_units: 190,
    price_from: 950000,
    price_to: 5200000,
    completion_date: 'Q1 2028',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-dev-008',
    name: 'JBR Waterfront',
    location: 'JBR, Dubai',
    status: 'Active',
    total_units: 210,
    available_units: 31,
    price_from: 1100000,
    price_to: 6000000,
    completion_date: 'Q2 2026',
    image_url: null,
    company_id: SB_DEMO_COMPANY.id,
  },
]

export const SB_DEMO_RECENT_LEADS = [
  {
    id: 'sb-lead-001',
    full_name: 'Khalid Al-Maktoum',
    first_name: 'Khalid',
    last_name: 'Al-Maktoum',
    email: 'khalid@maktoum-inv.ae',
    phone: '+971501234001',
    status: 'Negotiating',
    ai_quality_score: 95,
    ai_intent_score: 92,
    ai_confidence: 9.6,
    ai_classification: 'Hot Lead',
    ai_summary: 'Verified UHNW buyer with AED 25M+ portfolio. Wants 3-bed penthouse at Palm Residences. Cash buyer, ready to proceed.',
    budget_range: '$3M-$5M',
    development_name: 'Palm Residences',
    source_platform: 'referral',
    final_score: 94,
    created_at: '2026-02-14T10:30:00Z',
  },
  {
    id: 'sb-lead-002',
    full_name: 'Oliver Hartley',
    first_name: 'Oliver',
    last_name: 'Hartley',
    email: 'oliver.h@londoncap.co.uk',
    phone: '+447700200002',
    status: 'Viewing Booked',
    ai_quality_score: 89,
    ai_intent_score: 85,
    ai_confidence: 8.8,
    ai_classification: 'Hot Lead',
    ai_summary: 'UK-based property investor. Portfolio of 8 properties. Looking for Dubai Marina off-plan for rental yield. Proof of funds verified at £2.1M.',
    budget_range: '$1.5M-$2.5M',
    development_name: 'Dubai Marina Heights',
    source_platform: 'website',
    final_score: 88,
    created_at: '2026-02-13T14:20:00Z',
  },
  {
    id: 'sb-lead-003',
    full_name: 'Rajesh Patel',
    first_name: 'Rajesh',
    last_name: 'Patel',
    email: 'rajesh@patel-group.in',
    phone: '+919876500003',
    status: 'Follow Up',
    ai_quality_score: 84,
    ai_intent_score: 79,
    ai_confidence: 8.1,
    ai_classification: 'Hot Lead',
    ai_summary: 'Indian HNW investor expanding UAE portfolio. Currently owns 2 units in Business Bay. Interested in Creek Vista 2-bed for capital growth.',
    budget_range: '$800K-$1.2M',
    development_name: 'Creek Vista',
    source_platform: 'WhatsApp',
    final_score: 83,
    created_at: '2026-02-12T09:15:00Z',
  },
  {
    id: 'sb-lead-004',
    full_name: 'Sophie Laurent',
    first_name: 'Sophie',
    last_name: 'Laurent',
    email: 'sophie.l@parisprop.fr',
    phone: '+33612345004',
    status: 'Viewing Booked',
    ai_quality_score: 82,
    ai_intent_score: 80,
    ai_confidence: 8.0,
    ai_classification: 'Hot Lead',
    ai_summary: 'French investor relocating family to Dubai. Needs 4-bed villa or penthouse. Budget confirmed. Viewing scheduled at Palm Residences.',
    budget_range: '$2M-$4M',
    development_name: 'Palm Residences',
    source_platform: 'Bayut',
    final_score: 81,
    created_at: '2026-02-11T16:45:00Z',
  },
  {
    id: 'sb-lead-005',
    full_name: 'Chen Wei',
    first_name: 'Chen',
    last_name: 'Wei',
    email: 'chen.wei@shanghaivc.cn',
    phone: '+8613812345005',
    status: 'Contact Pending',
    ai_quality_score: 79,
    ai_intent_score: 73,
    ai_confidence: 7.5,
    ai_classification: 'Qualified',
    ai_summary: 'Chinese investor looking for Golden Visa eligible properties. Budget $750K+. Interested in Creek Vista and Yas Bay. 3-month timeline.',
    budget_range: '$750K-$1.5M',
    development_name: 'Creek Vista',
    source_platform: 'form',
    final_score: 77,
    created_at: '2026-02-10T11:30:00Z',
  },
  {
    id: 'sb-lead-006',
    full_name: 'James Mitchell',
    first_name: 'James',
    last_name: 'Mitchell',
    email: 'james.m@nycrealty.com',
    phone: '+12125551006',
    status: 'Follow Up',
    ai_quality_score: 76,
    ai_intent_score: 70,
    ai_confidence: 7.2,
    ai_classification: 'Qualified',
    ai_summary: 'US investor exploring Dubai market for the first time. Interested in off-plan opportunities at JBR Waterfront. Exploring mortgage options.',
    budget_range: '$1M-$2M',
    development_name: 'JBR Waterfront',
    source_platform: 'Google Ads',
    final_score: 74,
    created_at: '2026-02-09T13:00:00Z',
  },
  {
    id: 'sb-lead-007',
    full_name: 'Fatima Al-Hashimi',
    first_name: 'Fatima',
    last_name: 'Al-Hashimi',
    email: 'fatima@hashimi-inv.ae',
    phone: '+971551234007',
    status: 'Negotiating',
    ai_quality_score: 91,
    ai_intent_score: 89,
    ai_confidence: 9.0,
    ai_classification: 'Hot Lead',
    ai_summary: 'Local UAE buyer upgrading from apartment to Saadiyat villa. Cash buyer with AED 15M budget. Solicitor already appointed.',
    budget_range: '$3M-$5M',
    development_name: 'Saadiyat Shores',
    source_platform: 'referral',
    final_score: 90,
    created_at: '2026-02-08T08:45:00Z',
  },
  {
    id: 'sb-lead-008',
    full_name: 'Thomas Schneider',
    first_name: 'Thomas',
    last_name: 'Schneider',
    email: 'thomas@schneider-kapital.de',
    phone: '+491512345008',
    status: 'Contact Pending',
    ai_quality_score: 72,
    ai_intent_score: 65,
    ai_confidence: 6.8,
    ai_classification: 'Qualified',
    ai_summary: 'German family office looking to allocate $5M into Dubai real estate. Interested in bulk purchase of 3-4 units across developments.',
    budget_range: '$4M-$6M',
    development_name: 'Dubai Marina Heights',
    source_platform: 'LinkedIn',
    final_score: 70,
    created_at: '2026-02-07T15:20:00Z',
  },
]

export const SB_DEMO_TOP_CAMPAIGNS = [
  {
    id: 'sb-camp-001',
    campaign_name: 'Palm Residences - Meta MENA',
    name: 'Palm Residences - Meta MENA',
    development_name: 'Palm Residences',
    development: 'Palm Residences',
    platform: 'Meta',
    status: 'active',
    spend: 56000,
    leads: 234,
    cpl: 239.32,
    impressions: 1800000,
    clicks: 27000,
    ctr: 1.5,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-camp-002',
    campaign_name: 'Dubai Marina Heights - Google Premium',
    name: 'Dubai Marina Heights - Google Premium',
    development_name: 'Dubai Marina Heights',
    development: 'Dubai Marina Heights',
    platform: 'Google Ads',
    status: 'active',
    spend: 48500,
    leads: 189,
    cpl: 256.61,
    impressions: 1200000,
    clicks: 18000,
    ctr: 1.5,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-camp-003',
    campaign_name: 'Creek Vista - Bayut Featured',
    name: 'Creek Vista - Bayut Featured',
    development_name: 'Creek Vista',
    development: 'Creek Vista',
    platform: 'Bayut',
    status: 'active',
    spend: 38200,
    leads: 267,
    cpl: 143.07,
    impressions: 520000,
    clicks: 15600,
    ctr: 3.0,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-camp-004',
    campaign_name: 'Saadiyat Shores - LinkedIn HNW',
    name: 'Saadiyat Shores - LinkedIn HNW',
    development_name: 'Saadiyat Shores',
    development: 'Saadiyat Shores',
    platform: 'LinkedIn',
    status: 'active',
    spend: 32000,
    leads: 112,
    cpl: 285.71,
    impressions: 780000,
    clicks: 11700,
    ctr: 1.5,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-camp-005',
    campaign_name: 'JBR Waterfront - Property Finder',
    name: 'JBR Waterfront - Property Finder',
    development_name: 'JBR Waterfront',
    development: 'JBR Waterfront',
    platform: 'Property Finder',
    status: 'active',
    spend: 28500,
    leads: 156,
    cpl: 182.69,
    impressions: 420000,
    clicks: 12600,
    ctr: 3.0,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-camp-006',
    campaign_name: 'Canary Wharf Place - UK Launch',
    name: 'Canary Wharf Place - UK Launch',
    development_name: 'Canary Wharf Place',
    development: 'Canary Wharf Place',
    platform: 'Meta',
    status: 'active',
    spend: 15000,
    leads: 48,
    cpl: 312.50,
    impressions: 450000,
    clicks: 6750,
    ctr: 1.5,
    company_id: SB_DEMO_COMPANY.id,
  },
  {
    id: 'sb-camp-007',
    campaign_name: 'Yas Bay Towers - Dubai Radio',
    name: 'Yas Bay Towers - Dubai Radio',
    development_name: 'Yas Bay Towers',
    development: 'Yas Bay Towers',
    platform: 'Display',
    status: 'completed',
    spend: 11200,
    leads: 34,
    cpl: 329.41,
    impressions: 220000,
    clicks: 3300,
    ctr: 1.5,
    company_id: SB_DEMO_COMPANY.id,
  },
]

/** Full dashboard stats response shape */
export function getSBDemoDashboardStats() {
  return {
    stats: {
      buyers: SB_DEMO_BUYER_STATS,
      campaigns: SB_DEMO_CAMPAIGN_STATS,
    },
    recentLeads: SB_DEMO_RECENT_LEADS,
    topCampaigns: SB_DEMO_TOP_CAMPAIGNS,
    userType: 'developer',
    loadTimeMs: 42,
  }
}
