import type { Buyer, Campaign, Company, DashboardMetrics } from '@/types'

// Dashboard metrics for admin view
export const dashboardMetrics: DashboardMetrics & { qualifiedRate: number } = {
  totalLeads: 1543,
  hotLeads: 127,
  avgScore: 72,
  totalSpend: 284500,
  avgCPL: 45,
  totalCampaigns: 57,
  activeCampaigns: 23,
  totalCompanies: 12,
  qualifiedRate: 68,
}

// Lead classifications for pie chart
export const leadClassifications = {
  hot: 127,
  star: 234,
  lightning: 412,
  valid: 523,
  cold: 247,
}

// Conversion funnel data
export const funnelData = [
  { name: 'Leads', value: 1543, color: '#ffffff' },
  { name: 'Qualified', value: 1049, color: '#22c55e' },
  { name: 'Contacted', value: 687, color: '#3b82f6' },
  { name: 'Viewing', value: 234, color: '#f59e0b' },
  { name: 'Offer', value: 89, color: '#a855f7' },
]

// Timeline data for area chart
export const timelineData = [
  { date: 'Jan', leads: 145 },
  { date: 'Feb', leads: 178 },
  { date: 'Mar', leads: 234 },
  { date: 'Apr', leads: 189 },
  { date: 'May', leads: 267 },
  { date: 'Jun', leads: 312 },
  { date: 'Jul', leads: 287 },
]

// Lead source data
export const sourceData = [
  { name: 'Meta Ads', value: 523 },
  { name: 'Google Ads', value: 412 },
  { name: 'Rightmove', value: 234 },
  { name: 'Zoopla', value: 187 },
  { name: 'Direct', value: 187 },
]

// AI recommendations
export const aiRecommendations = [
  'Increase Meta Ads budget by 15% - CPL trending 12% below average',
  'Follow up with James Chen (Score: 94) - Hasn\'t been contacted in 3 days',
  'Pause Google Display campaigns - CTR below threshold',
  'Priority viewing: Sarah Williams matched 3 new properties',
  'Berkeley Woolwich campaign needs creative refresh - engagement dropping',
]

// Campaign alerts
export const campaignAlerts = [
  {
    id: 'CA001',
    campaign: 'Berkeley Woolwich',
    currentCPL: 89,
    targetCPL: 45,
    recommendation: 'Reduce daily budget by 20%',
    savings: 2340,
  },
  {
    id: 'CA002',
    campaign: 'Regal Wembley',
    currentCPL: 67,
    targetCPL: 50,
    recommendation: 'Update ad creative',
    savings: 1200,
  },
]

// Action leads for admin dashboard
export const actionLeads = [
  {
    id: 'L001',
    name: 'James Chen',
    email: 'james.chen@email.com',
    phone: '+44 7911 123456',
    budget: '£800K-1M',
    timeline: 'Within 3 months',
    qualityScore: 94,
    intentScore: 91,
    status: 'Follow-up Required',
    source: 'Meta Ads',
    campaign: 'Berkeley Nine Elms',
  },
  {
    id: 'L002',
    name: 'Sarah Williams',
    email: 'sarah.w@email.com',
    phone: '+44 7911 234567',
    budget: '£1.2M-1.5M',
    timeline: 'Immediate',
    qualityScore: 89,
    intentScore: 95,
    status: 'Viewing Pending',
    source: 'Google Ads',
    campaign: 'Regal London',
  },
  {
    id: 'L003',
    name: 'David Park',
    email: 'd.park@email.com',
    phone: '+44 7911 345678',
    budget: '£600K-800K',
    timeline: 'Within 1 month',
    qualityScore: 86,
    intentScore: 88,
    status: 'Documentation',
    source: 'Rightmove',
    campaign: 'Mount Anvil',
  },
]

// Demo campaigns
export const demoCampaigns: Campaign[] = [
  {
    id: 'C001',
    name: 'Berkeley Nine Elms',
    client: 'Berkeley Group',
    platform: 'Meta',
    status: 'active',
    spend: 45000,
    leads: 234,
    cpl: 43,
    impressions: 1250000,
    clicks: 15600,
    ctr: 1.25,
    start_date: '2024-01-01',
  },
  {
    id: 'C002',
    name: 'Regal Wembley Park',
    client: 'Regal London',
    platform: 'Google',
    status: 'active',
    spend: 38000,
    leads: 189,
    cpl: 52,
    impressions: 980000,
    clicks: 12400,
    ctr: 1.27,
    start_date: '2024-02-15',
  },
  {
    id: 'C003',
    name: 'Mount Anvil Lewisham',
    client: 'Mount Anvil',
    platform: 'Meta',
    status: 'active',
    spend: 52000,
    leads: 312,
    cpl: 39,
    impressions: 1450000,
    clicks: 18900,
    ctr: 1.3,
    start_date: '2024-01-20',
  },
  {
    id: 'C004',
    name: 'Hadley Canary Wharf',
    client: 'Hadley Property',
    platform: 'Google',
    status: 'paused',
    spend: 28000,
    leads: 145,
    cpl: 48,
    impressions: 720000,
    clicks: 8900,
    ctr: 1.24,
    start_date: '2024-03-01',
  },
  {
    id: 'C005',
    name: 'JLL Westminster',
    client: 'JLL',
    platform: 'Meta',
    status: 'active',
    spend: 61000,
    leads: 287,
    cpl: 42,
    impressions: 1680000,
    clicks: 21200,
    ctr: 1.26,
    start_date: '2024-01-10',
  },
]

// Demo leads/buyers
export const demoLeads: Buyer[] = [
  {
    id: 'L001',
    full_name: 'James Chen',
    email: 'james.chen@email.com',
    phone: '+44 7911 123456',
    budget: '£800K-1M',
    budget_min: 800000,
    budget_max: 1000000,
    bedrooms: 2,
    location: 'South West London',
    timeline: 'Within 3 months',
    source: 'Meta Ads',
    campaign: 'Berkeley Nine Elms',
    status: 'Qualified',
    quality_score: 94,
    intent_score: 91,
    proof_of_funds: true,
    uk_broker: true,
    created_at: '2024-06-15',
    last_contact: '2024-06-20',
  },
  {
    id: 'L002',
    full_name: 'Sarah Williams',
    email: 'sarah.w@email.com',
    phone: '+44 7911 234567',
    budget: '£1.2M-1.5M',
    budget_min: 1200000,
    budget_max: 1500000,
    bedrooms: 3,
    location: 'Central London',
    timeline: 'Immediate',
    source: 'Google Ads',
    campaign: 'Regal London',
    status: 'Viewing Booked',
    quality_score: 89,
    intent_score: 95,
    proof_of_funds: true,
    uk_broker: true,
    uk_solicitor: true,
    created_at: '2024-06-10',
    last_contact: '2024-06-22',
  },
  {
    id: 'L003',
    full_name: 'David Park',
    email: 'd.park@email.com',
    phone: '+44 7911 345678',
    budget: '£600K-800K',
    budget_min: 600000,
    budget_max: 800000,
    bedrooms: 2,
    location: 'East London',
    timeline: 'Within 1 month',
    source: 'Rightmove',
    campaign: 'Mount Anvil',
    status: 'Documentation',
    quality_score: 86,
    intent_score: 88,
    proof_of_funds: false,
    uk_broker: true,
    created_at: '2024-06-08',
    last_contact: '2024-06-19',
  },
  {
    id: 'L004',
    full_name: 'Emma Thompson',
    email: 'emma.t@email.com',
    phone: '+44 7911 456789',
    budget: '£500K-600K',
    budget_min: 500000,
    budget_max: 600000,
    bedrooms: 1,
    location: 'North London',
    timeline: 'Within 6 months',
    source: 'Meta Ads',
    campaign: 'Hadley Property',
    status: 'New',
    quality_score: 72,
    intent_score: 65,
    proof_of_funds: false,
    created_at: '2024-06-20',
  },
  {
    id: 'L005',
    full_name: 'Michael Roberts',
    email: 'm.roberts@email.com',
    phone: '+44 7911 567890',
    budget: '£2M+',
    budget_min: 2000000,
    budget_max: 3000000,
    bedrooms: 4,
    location: 'Chelsea',
    timeline: 'Flexible',
    source: 'Direct',
    campaign: 'JLL Westminster',
    status: 'Qualified',
    quality_score: 91,
    intent_score: 78,
    proof_of_funds: true,
    uk_broker: true,
    uk_solicitor: true,
    created_at: '2024-06-05',
    last_contact: '2024-06-21',
  },
]

// Demo companies
export const demoCompanies: Company[] = [
  {
    id: 'CO001',
    name: 'Berkeley Group',
    type: 'Developer',
    contact_name: 'John Smith',
    contact_email: 'j.smith@berkeley.com',
    status: 'Active',
    total_spend: 145000,
    total_leads: 523,
    campaign_count: 8,
  },
  {
    id: 'CO002',
    name: 'Regal London',
    type: 'Developer',
    contact_name: 'Alice Brown',
    contact_email: 'a.brown@regallondon.com',
    status: 'Active',
    total_spend: 98000,
    total_leads: 345,
    campaign_count: 5,
  },
  {
    id: 'CO003',
    name: 'JLL',
    type: 'Agent',
    contact_name: 'Michael Davies',
    contact_email: 'm.davies@jll.com',
    status: 'Active',
    total_spend: 120000,
    total_leads: 456,
    campaign_count: 7,
  },
  {
    id: 'CO004',
    name: 'Mount Anvil',
    type: 'Developer',
    contact_name: 'Sarah Green',
    contact_email: 's.green@mountanvil.com',
    status: 'Active',
    total_spend: 87000,
    total_leads: 312,
    campaign_count: 4,
  },
]
