/**
 * Demo Data for Investor & Client Presentations
 *
 * Realistic sample data powering the demo dashboard.
 * Use /demo to enter presentation mode without Supabase credentials.
 */

export const DEMO_COMPANY = {
  id: 'demo-company-001',
  name: 'Meridian Developments',
  type: 'developer',
}

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@naybourhood.ai',
  name: 'Alex Carter',
  role: 'developer' as const,
  company: DEMO_COMPANY.name,
  company_id: DEMO_COMPANY.id,
  isDemo: true,
}

/** Dashboard stats matching the shape returned by /api/dashboard/stats */
export const DEMO_BUYER_STATS = {
  total_leads: 847,
  hot_leads: 92,
  qualified: 184,
  needs_qualification: 203,
  nurture: 246,
  low_priority: 98,
  disqualified: 24,
  avg_score: 64,
  contact_pending: 147,
  follow_up: 203,
  viewing_booked: 89,
  negotiating: 37,
  reserved: 18,
  completed: 12,
  not_proceeding: 54,
}

export const DEMO_CAMPAIGN_STATS = {
  total_campaigns: 12,
  active_campaigns: 7,
  total_spend: 184500,
  total_leads: 847,
  avg_cpl: 217.83,
}

export const DEMO_RECENT_LEADS = [
  {
    id: 'demo-lead-001',
    full_name: 'James Richardson',
    first_name: 'James',
    last_name: 'Richardson',
    email: 'james.r@meridian-inv.com',
    phone: '+447700100001',
    status: 'Viewing Booked',
    ai_quality_score: 92,
    ai_intent_score: 88,
    ai_confidence: 9.2,
    ai_classification: 'Hot Lead',
    ai_summary: 'Verified cash buyer with £2.8M budget. Viewing confirmed for Marine Heights penthouse. Solicitor instructed.',
    budget_range: '£2.5M-£3.5M',
    development_name: 'Marine Heights',
    source_platform: 'Rightmove',
    final_score: 91,
    created_at: '2026-02-14T10:30:00Z',
  },
  {
    id: 'demo-lead-002',
    full_name: 'Sarah Chen',
    first_name: 'Sarah',
    last_name: 'Chen',
    email: 'sarah.chen@hkmail.com',
    phone: '+85291234567',
    status: 'Follow Up',
    ai_quality_score: 87,
    ai_intent_score: 82,
    ai_confidence: 8.5,
    ai_classification: 'Hot Lead',
    ai_summary: 'Hong Kong-based investor, proof of funds verified. Looking for 2+ bed investment in Zone 1. Ready within 28 days.',
    budget_range: '£4M-£6M',
    development_name: 'Kensington Gate',
    source_platform: 'referral',
    final_score: 86,
    created_at: '2026-02-13T14:20:00Z',
  },
  {
    id: 'demo-lead-003',
    full_name: 'Mohammed Al-Rashid',
    first_name: 'Mohammed',
    last_name: 'Al-Rashid',
    email: 'mohammed@rashid-holdings.ae',
    phone: '+971501234567',
    status: 'Contact Pending',
    ai_quality_score: 84,
    ai_intent_score: 76,
    ai_confidence: 7.8,
    ai_classification: 'Hot Lead',
    ai_summary: 'UAE investor with verified £6M+ funds. Dependent studying at UCL. Needs 3-bed in Central London within 3 months.',
    budget_range: '£6M-£8M',
    development_name: 'The Residence WC1',
    source_platform: 'WhatsApp',
    final_score: 82,
    created_at: '2026-02-12T09:15:00Z',
  },
  {
    id: 'demo-lead-004',
    full_name: 'Emily Thornton',
    first_name: 'Emily',
    last_name: 'Thornton',
    email: 'emily.thornton@gmail.com',
    phone: '+447700100004',
    status: 'Negotiating',
    ai_quality_score: 90,
    ai_intent_score: 95,
    ai_confidence: 9.5,
    ai_classification: 'Hot Lead',
    ai_summary: 'UK-based primary residence buyer. Mortgage AIP secured at £1.8M. Solicitor instructed. Offer submitted on Marine Heights 3-bed.',
    budget_range: '£1.5M-£2M',
    development_name: 'Marine Heights',
    source_platform: 'website',
    final_score: 93,
    created_at: '2026-02-11T16:45:00Z',
  },
  {
    id: 'demo-lead-005',
    full_name: 'Michael Okonkwo',
    first_name: 'Michael',
    last_name: 'Okonkwo',
    email: 'michael.o@lagosventures.ng',
    phone: '+2348012345678',
    status: 'Follow Up',
    ai_quality_score: 78,
    ai_intent_score: 72,
    ai_confidence: 7.2,
    ai_classification: 'Hot Lead',
    ai_summary: 'Nigerian investor, cash buyer. Portfolio of 3 UK properties. Looking for East London new-build for BTL.',
    budget_range: '£1.8M-£2.2M',
    development_name: 'Canary Wharf Residences',
    source_platform: 'referral',
    final_score: 77,
    created_at: '2026-02-10T11:30:00Z',
  },
  {
    id: 'demo-lead-006',
    full_name: 'Alexandra Müller',
    first_name: 'Alexandra',
    last_name: 'Müller',
    email: 'a.muller@berlinprop.de',
    phone: '+491512345678',
    status: 'Viewing Booked',
    ai_quality_score: 82,
    ai_intent_score: 80,
    ai_confidence: 8.0,
    ai_classification: 'Hot Lead',
    ai_summary: 'German investor, proof of funds verified at €3.2M. UK solicitor engaged. Viewing 2 properties in SW London next week.',
    budget_range: '£2M-£3M',
    development_name: 'Chelsea Creek',
    source_platform: 'Zoopla',
    final_score: 82,
    created_at: '2026-02-09T13:00:00Z',
  },
  {
    id: 'demo-lead-007',
    full_name: 'Priya Sharma',
    first_name: 'Priya',
    last_name: 'Sharma',
    email: 'priya.sharma@mumbai-group.in',
    phone: '+919876543210',
    status: 'Contact Pending',
    ai_quality_score: 71,
    ai_intent_score: 65,
    ai_confidence: 6.8,
    ai_classification: 'Qualified',
    ai_summary: 'Indian investor, £1.5M budget. Dependent starting at Kings College. Needs 2-bed near Waterloo. 3-month timeline.',
    budget_range: '£1M-£2M',
    development_name: 'Southbank Place',
    source_platform: 'form',
    final_score: 69,
    created_at: '2026-02-08T08:45:00Z',
  },
  {
    id: 'demo-lead-008',
    full_name: 'David Osei',
    first_name: 'David',
    last_name: 'Osei',
    email: 'david.osei@accradev.gh',
    phone: '+233201234567',
    status: 'Follow Up',
    ai_quality_score: 68,
    ai_intent_score: 55,
    ai_confidence: 5.9,
    ai_classification: 'Qualified',
    ai_summary: 'Ghanaian buyer looking at off-plan investment. Budget £750K. Exploring mortgage options with UK broker. 6-month timeline.',
    budget_range: '£500k-£750k',
    development_name: 'Marine Heights',
    source_platform: 'WhatsApp',
    final_score: 63,
    created_at: '2026-02-07T15:20:00Z',
  },
]

export const DEMO_TOP_CAMPAIGNS = [
  {
    campaign_name: 'Marine Heights - Meta UK',
    development_name: 'Marine Heights',
    spend: 42500,
    leads: 187,
    cpl: 227.27,
    impressions: 1250000,
    clicks: 18750,
    ctr: 1.5,
  },
  {
    campaign_name: 'Kensington Gate - Google Premium',
    development_name: 'Kensington Gate',
    spend: 38200,
    leads: 142,
    cpl: 269.01,
    impressions: 980000,
    clicks: 14700,
    ctr: 1.5,
  },
  {
    campaign_name: 'Chelsea Creek - Meta International',
    development_name: 'Chelsea Creek',
    spend: 31800,
    leads: 156,
    cpl: 203.85,
    impressions: 2100000,
    clicks: 31500,
    ctr: 1.5,
  },
  {
    campaign_name: 'Marine Heights - Rightmove Featured',
    development_name: 'Marine Heights',
    spend: 28500,
    leads: 198,
    cpl: 143.94,
    impressions: 450000,
    clicks: 13500,
    ctr: 3.0,
  },
  {
    campaign_name: 'Canary Wharf - LinkedIn B2B',
    development_name: 'Canary Wharf Residences',
    spend: 22000,
    leads: 89,
    cpl: 247.19,
    impressions: 680000,
    clicks: 10200,
    ctr: 1.5,
  },
]

/** Full dashboard stats response shape */
export function getDemoDashboardStats() {
  return {
    stats: {
      buyers: DEMO_BUYER_STATS,
      campaigns: DEMO_CAMPAIGN_STATS,
    },
    recentLeads: DEMO_RECENT_LEADS,
    topCampaigns: DEMO_TOP_CAMPAIGNS,
    userType: 'developer',
    loadTimeMs: 47,
  }
}
