// Mount Anvil Demo Data for Naybourhood Pitch Meeting
// Demonstrates buyer intelligence platform capabilities

import { Buyer, Campaign, Development, DashboardMetrics } from '@/types'

// =====================================================
// DEMO USER ACCOUNTS
// =====================================================
export interface DemoUser {
  id: string
  email: string
  password: string
  firstName: string
  lastName: string
  role: string
  avatarUrl?: string
}

export const DEMO_USERS: DemoUser[] = [
  {
    id: 'demo-rowena',
    email: 'rowena@mountanvil.com',
    password: 'demo2026',
    firstName: 'Rowena',
    lastName: 'Chen',
    role: 'Sales Director',
  },
  {
    id: 'demo-jay',
    email: 'jay@mountanvil.com',
    password: 'demo2026',
    firstName: 'Jay',
    lastName: 'Patel',
    role: 'Head of Marketing',
  },
]

// =====================================================
// MOUNT ANVIL DEVELOPMENTS
// =====================================================
export const DEMO_DEVELOPMENTS: Development[] = [
  {
    id: 'dev-one-clapham',
    name: 'One Clapham',
    location: 'Clapham, SW4',
    address: '110 Clapham High Street, London SW4 7UL',
    developer: 'Mount Anvil',
    status: 'Selling',
    units: 85,
    total_units: 85,
    available_units: 32,
    price_from: '450000',
    price_to: '1200000',
    completion_date: '2026-Q4',
    description: 'A stunning collection of 1, 2 and 3 bedroom apartments in the heart of Clapham. Steps from the Common, with excellent transport links.',
    image_url: '/images/one-clapham.jpg',
    features: ['Concierge', 'Residents Gym', 'Rooftop Terrace', 'Cycle Storage'],
    total_leads: 38,
    ad_spend: 45000,
  },
  {
    id: 'dev-the-edit',
    name: 'The Edit',
    location: 'Nine Elms, SW8',
    address: 'Embassy Gardens, Nine Elms Lane, London SW8 5NQ',
    developer: 'Mount Anvil',
    status: 'Selling',
    units: 120,
    total_units: 120,
    available_units: 54,
    price_from: '550000',
    price_to: '1500000',
    completion_date: '2027-Q2',
    description: 'Premium studios to 3-bedroom apartments in Nine Elms. Part of the Embassy Gardens development with Sky Pool access.',
    image_url: '/images/the-edit.jpg',
    features: ['Sky Pool Access', 'Private Cinema', '24hr Concierge', 'Residents Lounge'],
    total_leads: 42,
    ad_spend: 62000,
  },
]

// =====================================================
// DEMO CAMPAIGNS
// =====================================================
export const DEMO_CAMPAIGNS: Campaign[] = [
  // One Clapham Campaigns
  {
    id: 'camp-clapham-ftb',
    name: 'Clapham First-Time Buyers',
    development: 'One Clapham',
    development_id: 'dev-one-clapham',
    platform: 'Meta Ads',
    status: 'Active',
    spend: 18500,
    leads: 24,
    cpl: 771,
    impressions: 245000,
    clicks: 3200,
    ctr: 1.31,
    start_date: '2025-11-01',
    ai_health_score: 78,
    ai_performance_summary: 'Strong performance with first-time buyers. CPL trending down week-on-week.',
    ai_recommendations: ['Increase budget for weekend targeting', 'Test video creative for higher engagement'],
  },
  {
    id: 'camp-clapham-investors',
    name: 'International Investors SW4',
    development: 'One Clapham',
    development_id: 'dev-one-clapham',
    platform: 'LinkedIn',
    status: 'Active',
    spend: 12500,
    leads: 8,
    cpl: 1563,
    impressions: 85000,
    clicks: 890,
    ctr: 1.05,
    start_date: '2025-10-15',
    ai_health_score: 62,
    ai_performance_summary: 'Higher CPL but qualified investor leads. Strong conversion potential.',
    ai_recommendations: ['Narrow targeting to HNW audiences', 'Add case study content'],
  },
  {
    id: 'camp-clapham-mph',
    name: 'MPH Organic - Clapham',
    development: 'One Clapham',
    development_id: 'dev-one-clapham',
    platform: 'Million Pound Homes',
    status: 'Active',
    spend: 14000,
    leads: 6,
    cpl: 2333,
    impressions: 42000,
    clicks: 580,
    ctr: 1.38,
    start_date: '2025-09-01',
    ai_health_score: 71,
    ai_performance_summary: 'Premium leads from MPH portal. High intent buyers.',
    ai_recommendations: ['Refresh listing photography', 'Add virtual tour'],
  },
  // The Edit Campaigns
  {
    id: 'camp-edit-launch',
    name: 'Nine Elms Launch',
    development: 'The Edit',
    development_id: 'dev-the-edit',
    platform: 'Meta Ads',
    status: 'Active',
    spend: 28000,
    leads: 32,
    cpl: 875,
    impressions: 420000,
    clicks: 5800,
    ctr: 1.38,
    start_date: '2025-11-15',
    ai_health_score: 85,
    ai_performance_summary: 'Launch campaign exceeding targets. Strong brand awareness driving quality leads.',
    ai_recommendations: ['Scale budget 20%', 'Test lookalike audiences from hot leads'],
  },
  {
    id: 'camp-edit-china',
    name: 'Chinese Investor Outreach',
    development: 'The Edit',
    development_id: 'dev-the-edit',
    platform: 'WeChat/Juwai',
    status: 'Active',
    spend: 22000,
    leads: 6,
    cpl: 3667,
    impressions: 180000,
    clicks: 1200,
    ctr: 0.67,
    start_date: '2025-10-01',
    ai_health_score: 68,
    ai_performance_summary: 'High-value investor leads. Long sales cycle but strong conversion rate.',
    ai_recommendations: ['Partner with local agents', 'Host virtual viewing events'],
  },
  {
    id: 'camp-edit-lifestyle',
    name: 'The Edit - Lifestyle',
    development: 'The Edit',
    development_id: 'dev-the-edit',
    platform: 'TikTok',
    status: 'Active',
    spend: 12000,
    leads: 4,
    cpl: 3000,
    impressions: 890000,
    clicks: 12500,
    ctr: 1.40,
    start_date: '2025-12-01',
    ai_health_score: 52,
    ai_performance_summary: 'High engagement but needs qualification improvement. Young demographic.',
    ai_recommendations: ['Add pre-qualification questions', 'Test 30-35 age targeting'],
  },
]

// =====================================================
// DEMO BUYERS - ONE CLAPHAM (38 leads)
// =====================================================
const ONE_CLAPHAM_BUYERS: Buyer[] = [
  // HOT LEADS (4)
  {
    id: 'buyer-oc-001',
    full_name: 'Marcus Wellington',
    first_name: 'Marcus',
    last_name: 'Wellington',
    email: 'marcus.wellington@gmail.com',
    phone: '+44 7700 900123',
    country: 'United Kingdom',
    budget: '£750K - £900K',
    budget_min: 750000,
    budget_max: 900000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Clapham',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    proof_of_funds: true,
    mortgage_status: 'AIP Approved',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Viewing Booked',
    viewing_booked: true,
    viewing_date: '2026-01-22',
    viewing_intent_confirmed: true,
    ai_quality_score: 88,
    ai_intent_score: 92,
    ai_confidence: 0.94,
    ai_classification: 'Hot Lead',
    ai_summary: 'High-intent first-time buyer with AIP approval. Budget aligned for 2-bed. Viewing confirmed for Wednesday.',
    ai_next_action: 'Prepare viewing pack and send reminder',
    ai_risk_flags: [],
    ai_recommendations: ['Send parking information', 'Prepare comparable sold prices'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'yes',
    created_at: '2026-01-08T10:30:00Z',
    last_contact: '2026-01-18T14:20:00Z',
  },
  {
    id: 'buyer-oc-002',
    full_name: 'Priya Sharma',
    first_name: 'Priya',
    last_name: 'Sharma',
    email: 'priya.sharma@outlook.com',
    phone: '+44 7700 900456',
    country: 'United Kingdom',
    budget: '£500K - £650K',
    budget_min: 500000,
    budget_max: 650000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    preferred_location: 'SW4',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Cash',
    proof_of_funds: true,
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Negotiating',
    ai_quality_score: 91,
    ai_intent_score: 85,
    ai_confidence: 0.92,
    ai_classification: 'Hot Lead',
    ai_summary: 'Cash buyer ready to proceed. Negotiating on Plot 24. Very responsive, serious purchaser.',
    ai_next_action: 'Schedule call to discuss offer',
    ai_risk_flags: [],
    ai_recommendations: ['Highlight Help to Buy alternative units', 'Prepare solicitor referral'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'introduced',
    viewing_booked: true,
    viewing_date: '2026-01-15',
    viewing_intent_confirmed: true,
    created_at: '2026-01-05T09:15:00Z',
    last_contact: '2026-01-19T11:45:00Z',
  },
  {
    id: 'buyer-oc-003',
    full_name: 'James & Emma Thompson',
    first_name: 'James',
    last_name: 'Thompson',
    email: 'james.thompson@techcorp.co.uk',
    phone: '+44 7700 900789',
    country: 'United Kingdom',
    budget: '£900K - £1.1M',
    budget_min: 900000,
    budget_max: 1100000,
    bedrooms: 3,
    preferred_bedrooms: 3,
    preferred_location: 'Clapham Common',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    proof_of_funds: true,
    mortgage_status: 'AIP Approved',
    source: 'Million Pound Homes',
    source_platform: 'Million Pound Homes',
    source_campaign: 'MPH Organic - Clapham',
    campaign_id: 'camp-clapham-mph',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Reserved',
    ai_quality_score: 95,
    ai_intent_score: 98,
    ai_confidence: 0.97,
    ai_classification: 'Hot Lead',
    ai_summary: 'Family upsizing from 2-bed flat in Wandsworth. Reserved Plot 67 (3-bed). Mortgage approved, solicitors instructed.',
    ai_next_action: 'Chase solicitors for contract exchange timeline',
    ai_risk_flags: [],
    ai_recommendations: ['Send completion timeline', 'Introduce to residents community'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'yes',
    viewing_booked: true,
    created_at: '2025-12-10T14:00:00Z',
    last_contact: '2026-01-17T16:30:00Z',
  },
  {
    id: 'buyer-oc-004',
    full_name: 'David Okonkwo',
    first_name: 'David',
    last_name: 'Okonkwo',
    email: 'david.okonkwo@investcap.com',
    phone: '+44 7700 900234',
    country: 'United Kingdom',
    budget: '£600K - £800K',
    budget_min: 600000,
    budget_max: 800000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'South London',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    proof_of_funds: true,
    source: 'LinkedIn',
    source_platform: 'LinkedIn',
    source_campaign: 'International Investors SW4',
    campaign_id: 'camp-clapham-investors',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Viewing Booked',
    viewing_booked: true,
    viewing_date: '2026-01-23',
    viewing_intent_confirmed: true,
    ai_quality_score: 86,
    ai_intent_score: 78,
    ai_confidence: 0.89,
    ai_classification: 'Hot Lead',
    ai_summary: 'BTL investor with existing portfolio. Looking at 2-beds for rental yield. Cash buyer, quick decision maker.',
    ai_next_action: 'Prepare rental yield projections',
    ai_risk_flags: [],
    ai_recommendations: ['Share rental comps', 'Discuss property management'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'yes',
    created_at: '2026-01-10T11:20:00Z',
    last_contact: '2026-01-18T09:15:00Z',
  },
  // QUALIFIED LEADS (6)
  {
    id: 'buyer-oc-005',
    full_name: 'Sophie Chen',
    first_name: 'Sophie',
    last_name: 'Chen',
    email: 'sophie.chen@gmail.com',
    phone: '+44 7700 900345',
    country: 'United Kingdom',
    budget: '£450K - £550K',
    budget_min: 450000,
    budget_max: 550000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    preferred_location: 'Clapham',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Researching',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 72,
    ai_intent_score: 65,
    ai_confidence: 0.78,
    ai_classification: 'Qualified',
    ai_summary: 'First-time buyer, needs mortgage advice. Budget at entry level. Interested but needs hand-holding.',
    ai_next_action: 'Connect with mortgage broker',
    ai_risk_flags: ['no_finance_confirmation'],
    ai_recommendations: ['Introduce broker', 'Send Help to Buy info'],
    replied: true,
    uk_broker: 'unknown',
    uk_solicitor: 'unknown',
    created_at: '2026-01-12T16:45:00Z',
    last_contact: '2026-01-16T10:30:00Z',
  },
  {
    id: 'buyer-oc-006',
    full_name: 'Alex Dubois',
    first_name: 'Alex',
    last_name: 'Dubois',
    email: 'alex.dubois@outlook.fr',
    phone: '+33 6 12 34 56 78',
    country: 'France',
    budget: '£700K - £900K',
    budget_min: 700000,
    budget_max: 900000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'London SW',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    proof_of_funds: false,
    source: 'LinkedIn',
    source_platform: 'LinkedIn',
    source_campaign: 'International Investors SW4',
    campaign_id: 'camp-clapham-investors',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 68,
    ai_intent_score: 62,
    ai_confidence: 0.71,
    ai_classification: 'Qualified',
    ai_summary: 'French investor, relocating for work. Needs UK bank account setup advice. Genuine buyer.',
    ai_next_action: 'Schedule video call',
    ai_risk_flags: ['overseas_buyer', 'no_finance_confirmation'],
    ai_recommendations: ['Send non-resident buying guide', 'Introduce to solicitor'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'no',
    created_at: '2026-01-08T13:00:00Z',
    last_contact: '2026-01-14T15:20:00Z',
  },
  {
    id: 'buyer-oc-007',
    full_name: 'Rachel Green',
    first_name: 'Rachel',
    last_name: 'Green',
    email: 'rachel.green@nhs.net',
    phone: '+44 7700 900567',
    country: 'United Kingdom',
    budget: '£500K - £700K',
    budget_min: 500000,
    budget_max: 700000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Clapham',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'AIP Approved',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 74,
    ai_intent_score: 58,
    ai_confidence: 0.76,
    ai_classification: 'Qualified',
    ai_summary: 'NHS doctor, stable income. AIP in place. Waiting for bonus confirmation before proceeding.',
    ai_next_action: 'Follow up in 2 weeks re: bonus',
    ai_risk_flags: [],
    ai_recommendations: ['Set reminder for Feb follow-up', 'Send new release availability'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'unknown',
    created_at: '2026-01-06T10:00:00Z',
    last_contact: '2026-01-13T14:00:00Z',
  },
  {
    id: 'buyer-oc-008',
    full_name: 'Michael Zhang',
    first_name: 'Michael',
    last_name: 'Zhang',
    email: 'michael.zhang@alumni.lse.ac.uk',
    phone: '+44 7700 900678',
    country: 'United Kingdom',
    budget: '£550K - £750K',
    budget_min: 550000,
    budget_max: 750000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    preferred_location: 'SW4 / SW11',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Researching',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Viewing Booked',
    viewing_booked: true,
    viewing_date: '2026-01-25',
    viewing_intent_confirmed: true,
    ai_quality_score: 71,
    ai_intent_score: 70,
    ai_confidence: 0.74,
    ai_classification: 'Qualified',
    ai_summary: 'Young professional, first-time buyer. Comparing with Battersea Power Station. Price conscious.',
    ai_next_action: 'Prepare comparison sheet',
    ai_risk_flags: ['comparing_competitors'],
    ai_recommendations: ['Highlight transport links', 'Emphasize service charge value'],
    replied: true,
    uk_broker: 'unknown',
    uk_solicitor: 'unknown',
    created_at: '2026-01-09T11:30:00Z',
    last_contact: '2026-01-17T16:45:00Z',
  },
  {
    id: 'buyer-oc-009',
    full_name: 'Hannah & Tom Morris',
    first_name: 'Hannah',
    last_name: 'Morris',
    email: 'hannah.morris@gmail.com',
    phone: '+44 7700 900890',
    country: 'United Kingdom',
    budget: '£850K - £1M',
    budget_min: 850000,
    budget_max: 1000000,
    bedrooms: 3,
    preferred_bedrooms: 3,
    preferred_location: 'Clapham',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'AIP Approved',
    proof_of_funds: true,
    source: 'Million Pound Homes',
    source_platform: 'Million Pound Homes',
    source_campaign: 'MPH Organic - Clapham',
    campaign_id: 'camp-clapham-mph',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 76,
    ai_intent_score: 64,
    ai_confidence: 0.79,
    ai_classification: 'Qualified',
    ai_summary: 'Growing family, need to sell current property first. Chain dependent but serious buyers.',
    ai_next_action: 'Check in on sale progress',
    ai_risk_flags: ['chain_dependent'],
    ai_recommendations: ['Discuss part-exchange options', 'Connect with selling agent'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'yes',
    created_at: '2026-01-04T09:45:00Z',
    last_contact: '2026-01-15T11:00:00Z',
  },
  {
    id: 'buyer-oc-010',
    full_name: 'Fatima Al-Hassan',
    first_name: 'Fatima',
    last_name: 'Al-Hassan',
    email: 'fatima.alhassan@gmail.com',
    phone: '+44 7700 900901',
    country: 'United Kingdom',
    budget: '£600K - £750K',
    budget_min: 600000,
    budget_max: 750000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Clapham',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Researching',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 69,
    ai_intent_score: 61,
    ai_confidence: 0.72,
    ai_classification: 'Qualified',
    ai_summary: 'Teacher relocating from Birmingham. Needs mortgage guidance for London market.',
    ai_next_action: 'Send mortgage comparison',
    ai_risk_flags: ['no_finance_confirmation'],
    ai_recommendations: ['Connect with broker', 'Share area guide'],
    replied: true,
    uk_broker: 'unknown',
    uk_solicitor: 'unknown',
    created_at: '2026-01-11T14:30:00Z',
    last_contact: '2026-01-16T09:00:00Z',
  },
  // NEEDS QUALIFICATION (5) - WhatsApp leads, low confidence
  {
    id: 'buyer-oc-011',
    full_name: 'John Smith',
    first_name: 'John',
    last_name: 'Smith',
    email: '',
    phone: '+44 7700 900012',
    country: 'United Kingdom',
    budget: '',
    timeline: '',
    purpose: '',
    source: 'WhatsApp',
    source_platform: 'WhatsApp',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Contact Pending',
    ai_quality_score: 35,
    ai_intent_score: 42,
    ai_confidence: 0.38,
    ai_classification: 'Needs Qualification',
    ai_summary: 'WhatsApp enquiry with minimal information. Needs full qualification call.',
    ai_next_action: 'Call to qualify',
    ai_risk_flags: ['incomplete_data', 'no_budget_info'],
    ai_recommendations: ['Attempt phone contact', 'Send qualification questions via WhatsApp'],
    replied: false,
    created_at: '2026-01-18T10:20:00Z',
  },
  {
    id: 'buyer-oc-012',
    full_name: 'Sarah Johnson',
    first_name: 'Sarah',
    last_name: 'Johnson',
    email: 'sarah.j.london@gmail.com',
    phone: '+44 7700 900023',
    country: 'United Kingdom',
    budget: '£400K - £500K',
    budget_min: 400000,
    budget_max: 500000,
    timeline: '',
    purpose: '',
    source: 'WhatsApp',
    source_platform: 'WhatsApp',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Contact Pending',
    ai_quality_score: 42,
    ai_intent_score: 38,
    ai_confidence: 0.45,
    ai_classification: 'Needs Qualification',
    ai_summary: 'Budget slightly below development minimum. Needs clarification on flexibility.',
    ai_next_action: 'Qualify budget and timeline',
    ai_risk_flags: ['budget_mismatch'],
    ai_recommendations: ['Discuss finance options', 'Present entry-level units'],
    replied: false,
    created_at: '2026-01-17T15:40:00Z',
  },
  {
    id: 'buyer-oc-013',
    full_name: 'Unknown',
    first_name: '',
    last_name: '',
    email: '',
    phone: '+44 7700 900034',
    country: 'United Kingdom',
    source: 'WhatsApp',
    source_platform: 'WhatsApp',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Contact Pending',
    ai_quality_score: 25,
    ai_intent_score: 30,
    ai_confidence: 0.28,
    ai_classification: 'Needs Qualification',
    ai_summary: 'Minimal data - only phone number captured. High risk of low quality.',
    ai_next_action: 'Attempt contact',
    ai_risk_flags: ['incomplete_data', 'no_name', 'no_budget_info'],
    ai_recommendations: ['Send intro message', 'Request callback'],
    replied: false,
    created_at: '2026-01-19T09:10:00Z',
  },
  {
    id: 'buyer-oc-014',
    full_name: 'Robert Wilson',
    first_name: 'Robert',
    last_name: 'Wilson',
    email: 'rwilson442@yahoo.com',
    phone: '+44 7700 900045',
    country: 'United Kingdom',
    budget: '£500K - £600K',
    budget_min: 500000,
    budget_max: 600000,
    timeline: '6+ months',
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    source: 'Form',
    source_platform: 'Landing Page',
    source_campaign: 'International Investors SW4',
    campaign_id: 'camp-clapham-investors',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Contact Pending',
    ai_quality_score: 48,
    ai_intent_score: 35,
    ai_confidence: 0.52,
    ai_classification: 'Needs Qualification',
    ai_summary: 'Long timeline, unclear motivation. Needs qualification to assess seriousness.',
    ai_next_action: 'Qualification call',
    ai_risk_flags: ['long_timeline', 'no_finance_confirmation'],
    ai_recommendations: ['Assess investment criteria', 'Determine portfolio size'],
    replied: false,
    created_at: '2026-01-16T11:50:00Z',
  },
  {
    id: 'buyer-oc-015',
    full_name: 'Emma Davis',
    first_name: 'Emma',
    last_name: 'Davis',
    email: 'emma.davis.property@hotmail.com',
    phone: '+44 7700 900056',
    country: 'United Kingdom',
    budget: '£700K - £800K',
    budget_min: 700000,
    budget_max: 800000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    timeline: '',
    purpose: '',
    source: 'WhatsApp',
    source_platform: 'WhatsApp',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Contact Pending',
    ai_quality_score: 52,
    ai_intent_score: 48,
    ai_confidence: 0.55,
    ai_classification: 'Needs Qualification',
    ai_summary: 'Good budget, missing timeline and purpose. Worth qualifying.',
    ai_next_action: 'Complete qualification',
    ai_risk_flags: ['incomplete_data'],
    ai_recommendations: ['Call to complete profile', 'Confirm payment method'],
    replied: false,
    created_at: '2026-01-15T16:30:00Z',
  },
  // NURTURE (3)
  {
    id: 'buyer-oc-016',
    full_name: 'Oliver Brown',
    first_name: 'Oliver',
    last_name: 'Brown',
    email: 'oliver.brown@uni.ac.uk',
    phone: '+44 7700 900067',
    country: 'United Kingdom',
    budget: '£450K - £550K',
    budget_min: 450000,
    budget_max: 550000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    preferred_location: 'Clapham',
    timeline: '6+ months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Not Started',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 58,
    ai_intent_score: 42,
    ai_confidence: 0.64,
    ai_classification: 'Nurture',
    ai_summary: 'PhD student finishing in 6 months. Good prospect for later in year. Keep warm.',
    ai_next_action: 'Add to nurture sequence',
    ai_risk_flags: ['long_timeline'],
    ai_recommendations: ['Monthly email updates', 'Invite to events'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'no',
    created_at: '2026-01-03T14:20:00Z',
    last_contact: '2026-01-10T12:00:00Z',
  },
  {
    id: 'buyer-oc-017',
    full_name: 'Lisa Turner',
    first_name: 'Lisa',
    last_name: 'Turner',
    email: 'lisa.turner@consultancy.com',
    phone: '+44 7700 900078',
    country: 'United Kingdom',
    budget: '£800K - £1M',
    budget_min: 800000,
    budget_max: 1000000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Clapham',
    timeline: '6+ months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Researching',
    source: 'Million Pound Homes',
    source_platform: 'Million Pound Homes',
    source_campaign: 'MPH Organic - Clapham',
    campaign_id: 'camp-clapham-mph',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 65,
    ai_intent_score: 45,
    ai_confidence: 0.68,
    ai_classification: 'Nurture',
    ai_summary: 'High budget but waiting for promotion decision. Strong future buyer.',
    ai_next_action: 'Schedule check-in Q2',
    ai_risk_flags: ['long_timeline'],
    ai_recommendations: ['Add to VIP list', 'Invite to exclusive previews'],
    replied: true,
    uk_broker: 'unknown',
    uk_solicitor: 'unknown',
    created_at: '2026-01-02T10:45:00Z',
    last_contact: '2026-01-08T16:00:00Z',
  },
  {
    id: 'buyer-oc-018',
    full_name: 'Andrew & Kate Phillips',
    first_name: 'Andrew',
    last_name: 'Phillips',
    email: 'andrew.phillips@gmail.com',
    phone: '+44 7700 900089',
    country: 'United Kingdom',
    budget: '£950K - £1.2M',
    budget_min: 950000,
    budget_max: 1200000,
    bedrooms: 3,
    preferred_bedrooms: 3,
    preferred_location: 'SW London',
    timeline: '6+ months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'AIP Approved',
    proof_of_funds: true,
    source: 'LinkedIn',
    source_platform: 'LinkedIn',
    source_campaign: 'International Investors SW4',
    campaign_id: 'camp-clapham-investors',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Follow Up',
    ai_quality_score: 72,
    ai_intent_score: 48,
    ai_confidence: 0.75,
    ai_classification: 'Nurture',
    ai_summary: 'Excellent profile but committed to current rental until August. Will proceed when lease ends.',
    ai_next_action: 'Book July follow-up',
    ai_risk_flags: ['lease_commitment'],
    ai_recommendations: ['Reserve interest in Plot 71', 'Schedule July viewing'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'unknown',
    created_at: '2025-12-28T11:30:00Z',
    last_contact: '2026-01-05T14:15:00Z',
  },
  // LOW PRIORITY (2)
  {
    id: 'buyer-oc-019',
    full_name: 'Mark Stevens',
    first_name: 'Mark',
    last_name: 'Stevens',
    email: 'markstevens99@gmail.com',
    phone: '+44 7700 900090',
    country: 'United Kingdom',
    budget: '£200K - £300K',
    budget_min: 200000,
    budget_max: 300000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    timeline: 'Within 28 days',
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Not Proceeding',
    ai_quality_score: 28,
    ai_intent_score: 55,
    ai_confidence: 0.82,
    ai_classification: 'Low Priority',
    ai_summary: 'Budget significantly below minimum. Redirected to shared ownership schemes.',
    ai_next_action: 'Close - budget mismatch',
    ai_risk_flags: ['budget_mismatch'],
    ai_recommendations: ['Refer to shared ownership', 'Remove from active pipeline'],
    replied: true,
    created_at: '2026-01-14T09:00:00Z',
    last_contact: '2026-01-14T15:30:00Z',
  },
  {
    id: 'buyer-oc-020',
    full_name: 'Jennifer Adams',
    first_name: 'Jennifer',
    last_name: 'Adams',
    email: 'jen.adams@realtor.com',
    phone: '+44 7700 900100',
    country: 'United Kingdom',
    budget: '£600K - £800K',
    budget_min: 600000,
    budget_max: 800000,
    timeline: '3 months',
    purpose: '',
    source: 'Landing Page',
    source_platform: 'Landing Page',
    source_campaign: 'Clapham First-Time Buyers',
    campaign_id: 'camp-clapham-ftb',
    development_id: 'dev-one-clapham',
    development_name: 'One Clapham',
    status: 'Disqualified',
    ai_quality_score: 15,
    ai_intent_score: 20,
    ai_confidence: 0.88,
    ai_classification: 'Low Priority',
    ai_summary: 'Competitor agent fishing for information. Disqualified.',
    ai_next_action: 'Archive',
    ai_risk_flags: ['suspected_agent'],
    ai_recommendations: ['Block from future communications', 'Report to marketing'],
    replied: false,
    created_at: '2026-01-13T14:00:00Z',
  },
]

// =====================================================
// DEMO BUYERS - THE EDIT (42 leads)
// =====================================================
const THE_EDIT_BUYERS: Buyer[] = [
  // HOT LEADS (4) - Including the STANDOUT demo lead
  {
    id: 'buyer-te-001',
    full_name: 'Victoria Huang',
    first_name: 'Victoria',
    last_name: 'Huang',
    email: 'victoria.huang@hongkongbank.com',
    phone: '+852 9123 4567',
    country: 'Hong Kong',
    budget: '£800K - £1.2M',
    budget_min: 800000,
    budget_max: 1200000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Nine Elms',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Dependent studying',
    purchase_purpose: 'Dependent studying',
    payment_method: 'Cash',
    proof_of_funds: true,
    source: 'WeChat/Juwai',
    source_platform: 'WeChat/Juwai',
    source_campaign: 'Chinese Investor Outreach',
    campaign_id: 'camp-edit-china',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Negotiating',
    ai_quality_score: 94,
    ai_intent_score: 96,
    ai_confidence: 0.96,
    ai_classification: 'Hot Lead',
    ai_summary: 'PRIORITY: HK banker purchasing for daughter starting Imperial College Sept 2026. Cash buyer with proof of funds verified. Negotiating on Plot 89 (2-bed with balcony). Decision needed by Jan 25 due to visa timeline.',
    ai_next_action: 'Call TODAY - finalize offer',
    ai_risk_flags: ['time_sensitive_visa'],
    ai_recommendations: ['Priority call today', 'Prepare reservation docs', 'Confirm completion timeline works for Sept move-in'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'introduced',
    viewing_booked: true,
    viewing_date: '2026-01-20',
    viewing_intent_confirmed: true,
    created_at: '2026-01-05T08:00:00Z',
    last_contact: '2026-01-19T16:45:00Z',
    notes: 'Daughter Victoria Jr starting MSc Finance at Imperial. Mother making purchase decision. Very responsive on WeChat. Prefers evening calls (HK time = morning UK).',
  },
  {
    id: 'buyer-te-002',
    full_name: 'Sebastian Cole',
    first_name: 'Sebastian',
    last_name: 'Cole',
    email: 'seb.cole@privateequity.co.uk',
    phone: '+44 7700 900111',
    country: 'United Kingdom',
    budget: '£1M - £1.5M',
    budget_min: 1000000,
    budget_max: 1500000,
    bedrooms: 3,
    preferred_bedrooms: 3,
    preferred_location: 'Nine Elms',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Cash',
    proof_of_funds: true,
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Reserved',
    ai_quality_score: 97,
    ai_intent_score: 99,
    ai_confidence: 0.98,
    ai_classification: 'Hot Lead',
    ai_summary: 'Reserved Plot 112 (3-bed penthouse). PE professional, cash buyer. Solicitors instructed, targeting exchange by Feb.',
    ai_next_action: 'Chase solicitor for contract',
    ai_risk_flags: [],
    ai_recommendations: ['Weekly progress calls', 'Introduce to concierge team'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'yes',
    viewing_booked: true,
    created_at: '2025-12-15T10:00:00Z',
    last_contact: '2026-01-18T11:30:00Z',
  },
  {
    id: 'buyer-te-003',
    full_name: 'Amara Osei',
    first_name: 'Amara',
    last_name: 'Osei',
    email: 'amara.osei@investghana.com',
    phone: '+44 7700 900122',
    country: 'Ghana',
    budget: '£600K - £800K',
    budget_min: 600000,
    budget_max: 800000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Vauxhall / Nine Elms',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    proof_of_funds: true,
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Viewing Booked',
    viewing_booked: true,
    viewing_date: '2026-01-21',
    viewing_intent_confirmed: true,
    ai_quality_score: 85,
    ai_intent_score: 88,
    ai_confidence: 0.91,
    ai_classification: 'Hot Lead',
    ai_summary: 'Ghana-based investor, UK tax resident. Building London portfolio. Cash funds verified. Viewing tomorrow.',
    ai_next_action: 'Confirm viewing details',
    ai_risk_flags: [],
    ai_recommendations: ['Prepare rental projections', 'Discuss furnishing packages'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'yes',
    created_at: '2026-01-08T13:45:00Z',
    last_contact: '2026-01-19T10:00:00Z',
  },
  {
    id: 'buyer-te-004',
    full_name: 'Daniel & Maria Santos',
    first_name: 'Daniel',
    last_name: 'Santos',
    email: 'daniel.santos@consultant.eu',
    phone: '+44 7700 900133',
    country: 'Portugal',
    budget: '£700K - £950K',
    budget_min: 700000,
    budget_max: 950000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'SW London',
    timeline: 'Within 28 days',
    ready_within_28_days: true,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'AIP Approved',
    proof_of_funds: true,
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Negotiating',
    ai_quality_score: 82,
    ai_intent_score: 79,
    ai_confidence: 0.87,
    ai_classification: 'Hot Lead',
    ai_summary: 'Portuguese couple relocating to London permanently. Both work in consulting. AIP approved, negotiating on Plot 54.',
    ai_next_action: 'Negotiate price',
    ai_risk_flags: [],
    ai_recommendations: ['Discuss incentive package', 'Confirm mortgage timeline'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'introduced',
    viewing_booked: true,
    viewing_date: '2026-01-16',
    created_at: '2026-01-06T11:00:00Z',
    last_contact: '2026-01-18T15:20:00Z',
  },
  // QUALIFIED LEADS (6)
  {
    id: 'buyer-te-005',
    full_name: 'James Liu',
    first_name: 'James',
    last_name: 'Liu',
    email: 'james.liu@tech.cn',
    phone: '+86 138 0000 1234',
    country: 'China',
    budget: '£900K - £1.2M',
    budget_min: 900000,
    budget_max: 1200000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Nine Elms',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    source: 'WeChat/Juwai',
    source_platform: 'WeChat/Juwai',
    source_campaign: 'Chinese Investor Outreach',
    campaign_id: 'camp-edit-china',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 74,
    ai_intent_score: 68,
    ai_confidence: 0.76,
    ai_classification: 'Qualified',
    ai_summary: 'Shanghai tech executive. Interested in London investment. Needs UK legal/tax advice.',
    ai_next_action: 'Arrange tax consultation',
    ai_risk_flags: ['overseas_buyer', 'currency_transfer'],
    ai_recommendations: ['Connect with tax advisor', 'Explain SDLT implications'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'no',
    created_at: '2026-01-10T07:30:00Z',
    last_contact: '2026-01-15T14:00:00Z',
  },
  {
    id: 'buyer-te-006',
    full_name: 'Charlotte Edwards',
    first_name: 'Charlotte',
    last_name: 'Edwards',
    email: 'charlotte.edwards@lawfirm.co.uk',
    phone: '+44 7700 900144',
    country: 'United Kingdom',
    budget: '£550K - £700K',
    budget_min: 550000,
    budget_max: 700000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    preferred_location: 'Vauxhall',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'AIP Approved',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Viewing Booked',
    viewing_booked: true,
    viewing_date: '2026-01-24',
    viewing_intent_confirmed: true,
    ai_quality_score: 71,
    ai_intent_score: 66,
    ai_confidence: 0.74,
    ai_classification: 'Qualified',
    ai_summary: 'Junior partner at law firm. First-time buyer with solid income. Viewing booked Friday.',
    ai_next_action: 'Prepare for viewing',
    ai_risk_flags: [],
    ai_recommendations: ['Highlight transport to City', 'Discuss first-time buyer incentives'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'yes',
    created_at: '2026-01-11T16:00:00Z',
    last_contact: '2026-01-17T10:30:00Z',
  },
  {
    id: 'buyer-te-007',
    full_name: 'Ahmad Hassan',
    first_name: 'Ahmad',
    last_name: 'Hassan',
    email: 'ahmad.hassan@dubaiinvest.ae',
    phone: '+971 50 123 4567',
    country: 'UAE',
    budget: '£1M - £1.5M',
    budget_min: 1000000,
    budget_max: 1500000,
    bedrooms: 3,
    preferred_bedrooms: 3,
    preferred_location: 'Prime London',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    proof_of_funds: true,
    source: 'LinkedIn',
    source_platform: 'LinkedIn',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 76,
    ai_intent_score: 62,
    ai_confidence: 0.78,
    ai_classification: 'Qualified',
    ai_summary: 'Dubai-based investor with UK portfolio. Interested in premium units. Visit planned for Feb.',
    ai_next_action: 'Confirm Feb London visit',
    ai_risk_flags: ['overseas_buyer'],
    ai_recommendations: ['Book private viewing', 'Prepare portfolio overview'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'yes',
    created_at: '2026-01-07T09:00:00Z',
    last_contact: '2026-01-14T11:45:00Z',
  },
  {
    id: 'buyer-te-008',
    full_name: 'Emily Watson',
    first_name: 'Emily',
    last_name: 'Watson',
    email: 'emily.watson@creativeco.io',
    phone: '+44 7700 900155',
    country: 'United Kingdom',
    budget: '£600K - £800K',
    budget_min: 600000,
    budget_max: 800000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Nine Elms',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Researching',
    source: 'TikTok',
    source_platform: 'TikTok',
    source_campaign: 'The Edit - Lifestyle',
    campaign_id: 'camp-edit-lifestyle',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 64,
    ai_intent_score: 58,
    ai_confidence: 0.68,
    ai_classification: 'Qualified',
    ai_summary: 'Creative director, first-time buyer. Loved lifestyle content. Needs mortgage guidance.',
    ai_next_action: 'Connect with broker',
    ai_risk_flags: ['no_finance_confirmation'],
    ai_recommendations: ['Send lifestyle video', 'Introduce to broker'],
    replied: true,
    uk_broker: 'unknown',
    uk_solicitor: 'unknown',
    created_at: '2026-01-13T18:30:00Z',
    last_contact: '2026-01-16T12:00:00Z',
  },
  {
    id: 'buyer-te-009',
    full_name: 'Benjamin Park',
    first_name: 'Benjamin',
    last_name: 'Park',
    email: 'ben.park@samsung.kr',
    phone: '+82 10 1234 5678',
    country: 'South Korea',
    budget: '£700K - £900K',
    budget_min: 700000,
    budget_max: 900000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'London SW',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Dependent studying',
    purchase_purpose: 'Dependent studying',
    payment_method: 'Cash',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 68,
    ai_intent_score: 64,
    ai_confidence: 0.71,
    ai_classification: 'Qualified',
    ai_summary: 'Samsung executive, son starting Kings College Sept 2026. Comparing Nine Elms and Canary Wharf.',
    ai_next_action: 'Schedule video call',
    ai_risk_flags: ['overseas_buyer', 'comparing_competitors'],
    ai_recommendations: ['Highlight proximity to Kings', 'Send virtual tour'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'unknown',
    created_at: '2026-01-09T06:00:00Z',
    last_contact: '2026-01-13T09:30:00Z',
  },
  {
    id: 'buyer-te-010',
    full_name: 'Natalie Cooper',
    first_name: 'Natalie',
    last_name: 'Cooper',
    email: 'natalie.cooper@finance.com',
    phone: '+44 7700 900166',
    country: 'United Kingdom',
    budget: '£650K - £850K',
    budget_min: 650000,
    budget_max: 850000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Nine Elms',
    timeline: '3 months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'AIP Approved',
    proof_of_funds: true,
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 73,
    ai_intent_score: 65,
    ai_confidence: 0.75,
    ai_classification: 'Qualified',
    ai_summary: 'Finance professional with AIP. Waiting for Q1 bonus to confirm deposit. March decision likely.',
    ai_next_action: 'Schedule March check-in',
    ai_risk_flags: ['bonus_dependent'],
    ai_recommendations: ['Set March reminder', 'Discuss reservation to hold unit'],
    replied: true,
    uk_broker: 'yes',
    uk_solicitor: 'unknown',
    created_at: '2026-01-04T14:00:00Z',
    last_contact: '2026-01-12T16:30:00Z',
  },
  // NEEDS QUALIFICATION (5)
  {
    id: 'buyer-te-011',
    full_name: 'WeChat User 8821',
    first_name: '',
    last_name: '',
    email: '',
    phone: '+86 139 8821 0000',
    country: 'China',
    budget: '',
    source: 'WeChat/Juwai',
    source_platform: 'WeChat/Juwai',
    source_campaign: 'Chinese Investor Outreach',
    campaign_id: 'camp-edit-china',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Contact Pending',
    ai_quality_score: 32,
    ai_intent_score: 40,
    ai_confidence: 0.35,
    ai_classification: 'Needs Qualification',
    ai_summary: 'WeChat enquiry, minimal info. Language barrier possible. Needs Mandarin-speaking agent.',
    ai_next_action: 'Assign to Mandarin team',
    ai_risk_flags: ['incomplete_data', 'language_barrier'],
    ai_recommendations: ['Forward to Mandarin agent', 'Send WeChat intro in Chinese'],
    replied: false,
    created_at: '2026-01-18T03:00:00Z',
  },
  {
    id: 'buyer-te-012',
    full_name: 'Alex Martinez',
    first_name: 'Alex',
    last_name: 'Martinez',
    email: 'alex.m.2026@gmail.com',
    phone: '+44 7700 900177',
    country: 'United Kingdom',
    budget: '£500K - £600K',
    budget_min: 500000,
    budget_max: 600000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    timeline: '',
    purpose: '',
    source: 'TikTok',
    source_platform: 'TikTok',
    source_campaign: 'The Edit - Lifestyle',
    campaign_id: 'camp-edit-lifestyle',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Contact Pending',
    ai_quality_score: 45,
    ai_intent_score: 42,
    ai_confidence: 0.48,
    ai_classification: 'Needs Qualification',
    ai_summary: 'TikTok lead, younger demographic. Budget at entry level. Qualify timeline and seriousness.',
    ai_next_action: 'Qualification call',
    ai_risk_flags: ['incomplete_data', 'young_demographic'],
    ai_recommendations: ['Assess affordability', 'Discuss shared ownership if needed'],
    replied: false,
    created_at: '2026-01-17T20:15:00Z',
  },
  {
    id: 'buyer-te-013',
    full_name: 'Ryan O\'Brien',
    first_name: 'Ryan',
    last_name: 'O\'Brien',
    email: 'ryan.obrien@startup.tech',
    phone: '+44 7700 900188',
    country: 'Ireland',
    budget: '£800K - £1M',
    budget_min: 800000,
    budget_max: 1000000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    timeline: '',
    purpose: '',
    source: 'Form',
    source_platform: 'Landing Page',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Contact Pending',
    ai_quality_score: 55,
    ai_intent_score: 50,
    ai_confidence: 0.58,
    ai_classification: 'Needs Qualification',
    ai_summary: 'Irish tech founder, good budget. Missing timeline and purpose. Worth qualifying.',
    ai_next_action: 'Complete profile',
    ai_risk_flags: ['incomplete_data'],
    ai_recommendations: ['Call to qualify', 'Determine primary vs investment'],
    replied: false,
    created_at: '2026-01-16T14:30:00Z',
  },
  {
    id: 'buyer-te-014',
    full_name: 'Unknown Caller',
    first_name: '',
    last_name: '',
    email: '',
    phone: '+44 7700 900199',
    country: 'United Kingdom',
    source: 'WhatsApp',
    source_platform: 'WhatsApp',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Contact Pending',
    ai_quality_score: 22,
    ai_intent_score: 28,
    ai_confidence: 0.25,
    ai_classification: 'Needs Qualification',
    ai_summary: 'WhatsApp only, no details. Low data quality. Attempt single contact then archive.',
    ai_next_action: 'One contact attempt',
    ai_risk_flags: ['incomplete_data', 'no_name', 'no_budget_info'],
    ai_recommendations: ['Single WhatsApp message', 'Archive if no response in 48h'],
    replied: false,
    created_at: '2026-01-19T11:45:00Z',
  },
  {
    id: 'buyer-te-015',
    full_name: 'Michelle Taylor',
    first_name: 'Michelle',
    last_name: 'Taylor',
    email: 'michelle.t.property@yahoo.co.uk',
    phone: '+44 7700 900200',
    country: 'United Kingdom',
    budget: '£700K - £850K',
    budget_min: 700000,
    budget_max: 850000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    timeline: '',
    purpose: '',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Contact Pending',
    ai_quality_score: 54,
    ai_intent_score: 48,
    ai_confidence: 0.56,
    ai_classification: 'Needs Qualification',
    ai_summary: 'Good budget alignment. Missing key qualification data. Standard qualification needed.',
    ai_next_action: 'Qualify fully',
    ai_risk_flags: ['incomplete_data'],
    ai_recommendations: ['Call to qualify', 'Confirm payment method'],
    replied: false,
    created_at: '2026-01-15T09:20:00Z',
  },
  // NURTURE (3)
  {
    id: 'buyer-te-016',
    full_name: 'George Thompson',
    first_name: 'George',
    last_name: 'Thompson',
    email: 'george.thompson@university.edu',
    phone: '+44 7700 900211',
    country: 'United Kingdom',
    budget: '£600K - £750K',
    budget_min: 600000,
    budget_max: 750000,
    bedrooms: 1,
    preferred_bedrooms: 1,
    preferred_location: 'Nine Elms',
    timeline: '6+ months',
    ready_within_28_days: false,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 62,
    ai_intent_score: 45,
    ai_confidence: 0.66,
    ai_classification: 'Nurture',
    ai_summary: 'University professor, inheritance funds arriving mid-year. Good future buyer.',
    ai_next_action: 'Add to nurture',
    ai_risk_flags: ['long_timeline', 'inheritance_pending'],
    ai_recommendations: ['Quarterly check-ins', 'Invite to investor events'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'unknown',
    created_at: '2026-01-02T11:00:00Z',
    last_contact: '2026-01-09T15:00:00Z',
  },
  {
    id: 'buyer-te-017',
    full_name: 'Claire & Robert Hughes',
    first_name: 'Claire',
    last_name: 'Hughes',
    email: 'claire.hughes@email.com',
    phone: '+44 7700 900222',
    country: 'United Kingdom',
    budget: '£900K - £1.1M',
    budget_min: 900000,
    budget_max: 1100000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'SW London',
    timeline: '6+ months',
    ready_within_28_days: false,
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    payment_method: 'Mortgage',
    mortgage_status: 'Not Started',
    source: 'LinkedIn',
    source_platform: 'LinkedIn',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 67,
    ai_intent_score: 48,
    ai_confidence: 0.70,
    ai_classification: 'Nurture',
    ai_summary: 'Couple planning relocation from Manchester. Both need new jobs in London first. H2 likely.',
    ai_next_action: 'Nurture sequence',
    ai_risk_flags: ['long_timeline', 'relocation_dependent'],
    ai_recommendations: ['Monthly updates', 'Share area guides'],
    replied: true,
    uk_broker: 'unknown',
    uk_solicitor: 'unknown',
    created_at: '2025-12-28T09:30:00Z',
    last_contact: '2026-01-06T14:00:00Z',
  },
  {
    id: 'buyer-te-018',
    full_name: 'Yuki Tanaka',
    first_name: 'Yuki',
    last_name: 'Tanaka',
    email: 'yuki.tanaka@japan.co.jp',
    phone: '+81 90 1234 5678',
    country: 'Japan',
    budget: '£800K - £1M',
    budget_min: 800000,
    budget_max: 1000000,
    bedrooms: 2,
    preferred_bedrooms: 2,
    preferred_location: 'Central London',
    timeline: '6+ months',
    ready_within_28_days: false,
    purpose: 'Investment',
    purchase_purpose: 'Investment',
    payment_method: 'Cash',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Follow Up',
    ai_quality_score: 64,
    ai_intent_score: 44,
    ai_confidence: 0.67,
    ai_classification: 'Nurture',
    ai_summary: 'Japanese investor, researching London market. Planning visit Q3. Long-term potential.',
    ai_next_action: 'Add to nurture',
    ai_risk_flags: ['long_timeline', 'overseas_buyer'],
    ai_recommendations: ['Send market reports', 'Invite to Tokyo event'],
    replied: true,
    uk_broker: 'no',
    uk_solicitor: 'no',
    created_at: '2025-12-20T04:00:00Z',
    last_contact: '2026-01-04T08:00:00Z',
  },
  // LOW PRIORITY (2)
  {
    id: 'buyer-te-019',
    full_name: 'Peter Jenkins',
    first_name: 'Peter',
    last_name: 'Jenkins',
    email: 'peter.jenkins.2020@outlook.com',
    phone: '+44 7700 900233',
    country: 'United Kingdom',
    budget: '£300K - £400K',
    budget_min: 300000,
    budget_max: 400000,
    bedrooms: 1,
    timeline: 'Within 28 days',
    purpose: 'Primary residence',
    purchase_purpose: 'Primary residence',
    source: 'TikTok',
    source_platform: 'TikTok',
    source_campaign: 'The Edit - Lifestyle',
    campaign_id: 'camp-edit-lifestyle',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Not Proceeding',
    ai_quality_score: 25,
    ai_intent_score: 52,
    ai_confidence: 0.80,
    ai_classification: 'Low Priority',
    ai_summary: 'Budget well below development minimum. Cannot proceed without significant change.',
    ai_next_action: 'Close',
    ai_risk_flags: ['budget_mismatch'],
    ai_recommendations: ['Redirect to other developments', 'Archive'],
    replied: true,
    created_at: '2026-01-12T19:00:00Z',
    last_contact: '2026-01-13T10:00:00Z',
  },
  {
    id: 'buyer-te-020',
    full_name: 'Sarah Property Investor',
    first_name: 'Sarah',
    last_name: 'Property Investor',
    email: 'info@propertyinvestmentagency.co.uk',
    phone: '+44 7700 900244',
    country: 'United Kingdom',
    budget: '£1M+',
    source: 'Form',
    source_platform: 'Landing Page',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: 'Disqualified',
    ai_quality_score: 12,
    ai_intent_score: 15,
    ai_confidence: 0.90,
    ai_classification: 'Low Priority',
    ai_summary: 'Buying agent seeking stock for clients. Not a direct buyer.',
    ai_next_action: 'Archive',
    ai_risk_flags: ['suspected_agent', 'agency_enquiry'],
    ai_recommendations: ['Redirect to sales team for agent program', 'Remove from buyer pipeline'],
    replied: false,
    created_at: '2026-01-11T10:00:00Z',
  },
  // Additional leads to reach 42 total for The Edit
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `buyer-te-${21 + i}`,
    full_name: [
      'William Chen', 'Isabella Moore', 'Thomas Wright', 'Olivia Brown', 'Henry Wilson',
      'Sophia Taylor', 'Jack Anderson', 'Mia Thomas', 'Charlie Jackson', 'Amelia White',
      'Oscar Harris', 'Lily Martin', 'Leo Thompson', 'Ava Garcia', 'Archie Martinez',
      'Grace Robinson', 'Freddie Clark', 'Chloe Rodriguez', 'Arthur Lewis', 'Ella Lee',
      'Theodore Walker', 'Ruby Hall'
    ][i],
    first_name: [
      'William', 'Isabella', 'Thomas', 'Olivia', 'Henry',
      'Sophia', 'Jack', 'Mia', 'Charlie', 'Amelia',
      'Oscar', 'Lily', 'Leo', 'Ava', 'Archie',
      'Grace', 'Freddie', 'Chloe', 'Arthur', 'Ella',
      'Theodore', 'Ruby'
    ][i],
    last_name: [
      'Chen', 'Moore', 'Wright', 'Brown', 'Wilson',
      'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White',
      'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez',
      'Robinson', 'Clark', 'Rodriguez', 'Lewis', 'Lee',
      'Walker', 'Hall'
    ][i],
    email: `${['william.chen', 'isabella.moore', 'thomas.wright', 'olivia.brown', 'henry.wilson',
      'sophia.taylor', 'jack.anderson', 'mia.thomas', 'charlie.jackson', 'amelia.white',
      'oscar.harris', 'lily.martin', 'leo.thompson', 'ava.garcia', 'archie.martinez',
      'grace.robinson', 'freddie.clark', 'chloe.rodriguez', 'arthur.lewis', 'ella.lee',
      'theodore.walker', 'ruby.hall'][i]}@email.com`,
    phone: `+44 7700 90${(300 + i).toString().padStart(4, '0')}`,
    country: ['United Kingdom', 'United Kingdom', 'China', 'United Kingdom', 'United Kingdom',
      'Germany', 'United Kingdom', 'France', 'United Kingdom', 'United Kingdom',
      'United Kingdom', 'Spain', 'United Kingdom', 'Italy', 'United Kingdom',
      'Netherlands', 'United Kingdom', 'United Kingdom', 'Singapore', 'United Kingdom',
      'Australia', 'United Kingdom'][i],
    budget: ['£600K - £750K', '£700K - £900K', '£550K - £700K', '£800K - £1M', '£650K - £800K',
      '£750K - £950K', '£600K - £800K', '£700K - £850K', '£550K - £700K', '£900K - £1.1M',
      '£600K - £750K', '£650K - £850K', '£700K - £900K', '£800K - £1M', '£550K - £700K',
      '£750K - £950K', '£600K - £800K', '£650K - £850K', '£900K - £1.2M', '£550K - £700K',
      '£700K - £900K', '£600K - £750K'][i],
    budget_min: [600000, 700000, 550000, 800000, 650000, 750000, 600000, 700000, 550000, 900000,
      600000, 650000, 700000, 800000, 550000, 750000, 600000, 650000, 900000, 550000, 700000, 600000][i],
    budget_max: [750000, 900000, 700000, 1000000, 800000, 950000, 800000, 850000, 700000, 1100000,
      750000, 850000, 900000, 1000000, 700000, 950000, 800000, 850000, 1200000, 700000, 900000, 750000][i],
    bedrooms: [1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1][i],
    preferred_bedrooms: [1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1][i],
    timeline: ['3 months', '3 months', '6+ months', 'Within 28 days', '3 months',
      '6+ months', '3 months', '3 months', '6+ months', 'Within 28 days',
      '3 months', '6+ months', '3 months', '3 months', '6+ months',
      'Within 28 days', '3 months', '3 months', '6+ months', '3 months',
      '6+ months', '3 months'][i],
    ready_within_28_days: [false, false, false, true, false, false, false, false, false, true,
      false, false, false, false, false, true, false, false, false, false, false, false][i],
    purpose: ['Primary residence', 'Investment', 'Investment', 'Primary residence', 'Primary residence',
      'Investment', 'Primary residence', 'Primary residence', 'Investment', 'Primary residence',
      'Primary residence', 'Investment', 'Primary residence', 'Primary residence', 'Investment',
      'Primary residence', 'Primary residence', 'Investment', 'Investment', 'Primary residence',
      'Investment', 'Primary residence'][i],
    purchase_purpose: ['Primary residence', 'Investment', 'Investment', 'Primary residence', 'Primary residence',
      'Investment', 'Primary residence', 'Primary residence', 'Investment', 'Primary residence',
      'Primary residence', 'Investment', 'Primary residence', 'Primary residence', 'Investment',
      'Primary residence', 'Primary residence', 'Investment', 'Investment', 'Primary residence',
      'Investment', 'Primary residence'][i],
    payment_method: ['Mortgage', 'Cash', 'Cash', 'Mortgage', 'Mortgage',
      'Cash', 'Mortgage', 'Mortgage', 'Cash', 'Mortgage',
      'Mortgage', 'Cash', 'Mortgage', 'Mortgage', 'Mortgage',
      'Cash', 'Mortgage', 'Mortgage', 'Cash', 'Mortgage',
      'Cash', 'Mortgage'][i] as 'Mortgage' | 'Cash',
    source: 'Meta Ads',
    source_platform: 'Meta Ads',
    source_campaign: 'Nine Elms Launch',
    campaign_id: 'camp-edit-launch',
    development_id: 'dev-the-edit',
    development_name: 'The Edit',
    status: ['Follow Up', 'Follow Up', 'Follow Up', 'Viewing Booked', 'Follow Up',
      'Follow Up', 'Follow Up', 'Follow Up', 'Contact Pending', 'Negotiating',
      'Follow Up', 'Follow Up', 'Follow Up', 'Follow Up', 'Contact Pending',
      'Viewing Booked', 'Follow Up', 'Follow Up', 'Follow Up', 'Contact Pending',
      'Follow Up', 'Follow Up'][i],
    ai_quality_score: [58, 62, 55, 72, 60, 64, 56, 61, 48, 78, 57, 59, 63, 66, 45, 74, 54, 58, 68, 42, 60, 55][i],
    ai_intent_score: [52, 58, 48, 68, 55, 50, 54, 56, 42, 74, 50, 52, 58, 60, 40, 70, 48, 54, 55, 38, 52, 50][i],
    ai_confidence: [0.62, 0.66, 0.58, 0.75, 0.64, 0.67, 0.60, 0.65, 0.52, 0.80, 0.61, 0.63, 0.67, 0.69, 0.48, 0.76, 0.58, 0.62, 0.70, 0.45, 0.65, 0.59][i],
    ai_classification: ['Qualified', 'Qualified', 'Nurture', 'Qualified', 'Qualified',
      'Nurture', 'Qualified', 'Qualified', 'Needs Qualification', 'Hot Lead',
      'Qualified', 'Nurture', 'Qualified', 'Qualified', 'Needs Qualification',
      'Qualified', 'Qualified', 'Qualified', 'Nurture', 'Needs Qualification',
      'Nurture', 'Qualified'][i],
    ai_summary: `${[
      'Good first-time buyer prospect. Needs mortgage confirmation.',
      'Investor with portfolio experience. Comparing yields.',
      'Chinese investor, researching market. Long timeline.',
      'Viewing booked, motivated buyer. Good match.',
      'Steady professional. Timeline aligned with bonus.',
      'German investor. Researching London market.',
      'First-time buyer. Mortgage pre-approval in progress.',
      'French national relocating. Budget aligned.',
      'New enquiry. Needs full qualification.',
      'Hot prospect - negotiating on Plot 78.',
      'First-time buyer. Good profile, needs nurturing.',
      'Spanish investor. Planning London visit.',
      'Young professional. Good budget match.',
      'Italian buyer. Relocating for work.',
      'Minimal data. Needs qualification.',
      'Viewing booked for next week. Motivated.',
      'Recent graduate. Saving for deposit.',
      'Investor looking at rental yields.',
      'Singapore investor. Strong budget.',
      'New lead. Qualification needed.',
      'Australian expat. Returning to UK.',
      'First-time buyer. Ready to proceed.'
    ][i]}`,
    ai_next_action: ['Connect with broker', 'Share yield projections', 'Add to nurture', 'Prepare viewing pack',
      'Set reminder for March', 'Send market info', 'Chase mortgage update', 'Schedule call',
      'Qualify fully', 'Finalize negotiation', 'Follow up', 'Book viewing',
      'Schedule viewing', 'Assist with relocation', 'Contact for qualification', 'Confirm viewing',
      'Discuss finance options', 'Share rental data', 'Arrange virtual tour', 'Attempt contact',
      'Welcome back to UK', 'Progress to viewing'][i],
    ai_risk_flags: i % 4 === 0 ? ['no_finance_confirmation'] : [],
    replied: i % 3 !== 2,
    created_at: new Date(Date.now() - (i + 1) * 86400000 * 2).toISOString(),
    last_contact: i % 3 !== 2 ? new Date(Date.now() - (i + 1) * 86400000).toISOString() : undefined,
  } as Buyer)),
]

// =====================================================
// COMBINED DEMO BUYERS
// =====================================================
export const DEMO_BUYERS: Buyer[] = [...ONE_CLAPHAM_BUYERS, ...THE_EDIT_BUYERS]

// =====================================================
// HELPER FUNCTIONS
// =====================================================
export function getDemoBuyersByDevelopment(developmentId: string): Buyer[] {
  return DEMO_BUYERS.filter(b => b.development_id === developmentId)
}

export function getDemoCampaignsByDevelopment(developmentId: string): Campaign[] {
  return DEMO_CAMPAIGNS.filter(c => c.development_id === developmentId)
}

export function getDemoMetrics(developmentId?: string): DashboardMetrics {
  const buyers = developmentId
    ? DEMO_BUYERS.filter(b => b.development_id === developmentId)
    : DEMO_BUYERS

  const campaigns = developmentId
    ? DEMO_CAMPAIGNS.filter(c => c.development_id === developmentId)
    : DEMO_CAMPAIGNS

  const hotLeads = buyers.filter(b => b.ai_classification === 'Hot Lead').length
  const qualifiedLeads = buyers.filter(b =>
    b.ai_classification === 'Hot Lead' ||
    b.ai_classification === 'Qualified'
  ).length

  const avgScore = buyers.length > 0
    ? Math.round(buyers.reduce((sum, b) => sum + (b.ai_quality_score || 0), 0) / buyers.length)
    : 0

  const totalSpend = campaigns.reduce((sum, c) => sum + (c.spend || 0), 0)
  const totalLeads = campaigns.reduce((sum, c) => sum + (c.leads || 0), 0)

  return {
    totalLeads: buyers.length,
    hotLeads,
    avgScore,
    totalSpend,
    avgCPL: totalLeads > 0 ? Math.round(totalSpend / totalLeads) : 0,
    totalCampaigns: campaigns.length,
    activeCampaigns: campaigns.filter(c => c.status === 'Active').length,
    qualifiedRate: buyers.length > 0 ? Math.round((qualifiedLeads / buyers.length) * 100) : 0,
  }
}

export function getClassificationCounts(developmentId?: string) {
  const buyers = developmentId
    ? DEMO_BUYERS.filter(b => b.development_id === developmentId)
    : DEMO_BUYERS

  return {
    hotLead: buyers.filter(b => b.ai_classification === 'Hot Lead').length,
    qualified: buyers.filter(b => b.ai_classification === 'Qualified').length,
    needsQualification: buyers.filter(b => b.ai_classification === 'Needs Qualification').length,
    nurture: buyers.filter(b => b.ai_classification === 'Nurture').length,
    lowPriority: buyers.filter(b => b.ai_classification === 'Low Priority').length,
  }
}

// Get the standout demo lead (Victoria Huang)
export function getStandoutLead(): Buyer {
  return DEMO_BUYERS.find(b => b.id === 'buyer-te-001')!
}

// Simulate hot lead alerts
export interface HotLeadAlert {
  id: string
  buyerId: string
  buyerName: string
  development: string
  message: string
  urgency: 'critical' | 'high' | 'medium'
  timestamp: string
}

export function getHotLeadAlerts(): HotLeadAlert[] {
  return [
    {
      id: 'alert-1',
      buyerId: 'buyer-te-001',
      buyerName: 'Victoria Huang',
      development: 'The Edit',
      message: 'Decision deadline Jan 25 - visa timeline dependent',
      urgency: 'critical',
      timestamp: new Date().toISOString(),
    },
    {
      id: 'alert-2',
      buyerId: 'buyer-oc-002',
      buyerName: 'Priya Sharma',
      development: 'One Clapham',
      message: 'Cash buyer negotiating - respond to offer today',
      urgency: 'high',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'alert-3',
      buyerId: 'buyer-te-003',
      buyerName: 'Amara Osei',
      development: 'The Edit',
      message: 'Viewing tomorrow - send confirmation',
      urgency: 'high',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
    },
  ]
}

// Behavioural analytics for lead profiles
export interface BehaviouralAnalytics {
  emailOpens: number
  brochureViews: number
  priceListViews: number
  floorPlanViews: number
  timeOnSite: string
  lastVisit: string
  pageViews: number
  virtualTourViews: number
}

export function getBehaviouralAnalytics(buyerId: string): BehaviouralAnalytics {
  // Simulated data based on buyer classification
  const buyer = DEMO_BUYERS.find(b => b.id === buyerId)
  const isHot = buyer?.ai_classification === 'Hot Lead'
  const isQualified = buyer?.ai_classification === 'Qualified'

  if (isHot) {
    return {
      emailOpens: 12 + Math.floor(Math.random() * 8),
      brochureViews: 5 + Math.floor(Math.random() * 4),
      priceListViews: 8 + Math.floor(Math.random() * 5),
      floorPlanViews: 6 + Math.floor(Math.random() * 4),
      timeOnSite: `${15 + Math.floor(Math.random() * 10)}m ${Math.floor(Math.random() * 60)}s`,
      lastVisit: 'Today',
      pageViews: 45 + Math.floor(Math.random() * 30),
      virtualTourViews: 3 + Math.floor(Math.random() * 3),
    }
  } else if (isQualified) {
    return {
      emailOpens: 5 + Math.floor(Math.random() * 5),
      brochureViews: 2 + Math.floor(Math.random() * 3),
      priceListViews: 3 + Math.floor(Math.random() * 4),
      floorPlanViews: 2 + Math.floor(Math.random() * 3),
      timeOnSite: `${5 + Math.floor(Math.random() * 8)}m ${Math.floor(Math.random() * 60)}s`,
      lastVisit: 'Yesterday',
      pageViews: 15 + Math.floor(Math.random() * 20),
      virtualTourViews: 1 + Math.floor(Math.random() * 2),
    }
  }

  return {
    emailOpens: Math.floor(Math.random() * 4),
    brochureViews: Math.floor(Math.random() * 2),
    priceListViews: Math.floor(Math.random() * 3),
    floorPlanViews: Math.floor(Math.random() * 2),
    timeOnSite: `${Math.floor(Math.random() * 5)}m ${Math.floor(Math.random() * 60)}s`,
    lastVisit: '3 days ago',
    pageViews: Math.floor(Math.random() * 10),
    virtualTourViews: 0,
  }
}
